### ISSUE TITLE
adding section is not possible

### ISSUE THREAD

**Issue by softwerft** [pluspol-interactive/templavoilaplus#108]
After reopen DS/TO the section is changed to container. When i try to use the FCE, i get the error "Section expected at field_section but not found"

**Comment by opi99** [comment]
Please tell me which version of TemplaVoilà! Plus and TYPO3 do you use.

I know I fixed in this part for TV+ 7.1.3 so if you use 7.1.3 the question would be: Does 7.1.2 worked?

**Comment by softwerft** [comment]
Hi. We use TYPO3 8.7.3 The Bug is since TV+ Version 7.1.3. 
In 7.1.2 it was possible to create sections.
We made an update because it was in 7.1.2 not possible to add entries in the section when we edit or create an new FCE on the page.

**Comment by opi99** [comment]
Was there a bugreport about that problem?

**Comment by softwerft** [comment]
No. We were not sure if the reason was our migration from TYPO3 6.2 and TV. So we try a new setup with TYPO3 8.7 and newest TV+.

**Comment by opi99** [comment]
Hmmm ok, but from description, the migration can't be the issue. ;)

At the moment I've no time, maybe end of next week. The commit 8603154eb66a35e1480fb7b5ee789cb135205713 should be the issue of this bugreport. It looks like it is in an area I didn't used yet. So maybe I need some help from you. Will contact you then.
Are you in the typo3 slack?

**Comment by softwerft** [comment]
i find a little bug in BackendTemplateMappingController.php Line 328. I think this have to be elseif instead of if

**Comment by opi99** [comment]
Yes this looks like a typo, can you fix it on your system and test?

**Comment by softwerft** [comment]
Of course. It fix the issue.

**Comment by opi99** [comment]
Ok and does the other issue still exists?

**Comment by softwerft** [comment]
Yes, i opened another issue for that.
