### ISSUE TITLE
Can't choose a category in news flexform

### ISSUE THREAD

**Issue by mhirdes** [pluspol-interactive/templavoilaplus#111]
Hey, first of all, you did a great job. Everything works as expected until now. Maybe one suggestion while converting:
Replace register:tx_templavoila_pi1 to register:tx_templavoilaplus_pi1 
I did this manually.

But I've got another issue. I can't select any category in the news flexform plugin settings. 

![22-08-_2017_14-22-28](https://user-images.githubusercontent.com/915162/29565406-14331d12-8746-11e7-8a39-54acf7db123b.jpg)

We got 3 backend languages and the flexform is shown in 3 languages. Maybe this is the problem, don't know. But if I deactivate templavoilaplus only one language is shown and also the category tree. I use TYPO3 8.4, news 6.0 and templavoilaplus 7.1.3.

Kind regards,
Marc

**Comment by opi99** [comment]
![screenshot_20170827_150130](https://user-images.githubusercontent.com/1672061/29750061-543abde2-8b39-11e7-8c6a-6b6226cf1b01.png)

Huh?

**Comment by opi99** [comment]
Hmmm, this error persists after disabling TV+

**Comment by opi99** [comment]
Ok, disabling and reenabling news resolved this error ... now I can look into your issue.

**Comment by opi99** [comment]
Ok, I get this issue also with disabled TV+

> TypeError: TYPO3.FormEngine is undefined ... SelectTree.js:145:13

This seams a rare race condition

**Comment by opi99** [comment]
https://forge.typo3.org/issues/82217

Closing this issue report as invalid.

**Comment by opi99** [comment]
Hmmm, ok, thats another issue to this problem. Reopening.

**Comment by opi99** [comment]
Ok, first part done.
But to get correct data from the Ajax call we need:
* add "flexFormCurrentLanguage" to ajaxCall (how do I "XClass!!" the SelectTreeElement.js?)
* XClass TYPO3\CMS\Backend\Controller\FormSelectTreeAjaxController
* and add support for "flexFormCurrentLanguage" in request
so we get then the correct select items tree.

**Comment by opi99** [comment]
Question: Can the category list depend on language?
