### ISSUE TITLE
In a Flexible Content Element, a field of type "Rich text editor for bodytext" stores extra paragraphs

### ISSUE THREAD

**Issue by ymauray** [pluspol-interactive/templavoilaplus#119]
I have an FCE in which I've defined a field mapped to the inside of a div.
The element preset for this field is "Rich text editor for bodytext"

![image](https://user-images.githubusercontent.com/2527227/30053509-68119c22-9229-11e7-9bfc-2309a5c2f082.png)

Now I add this FCE to a page, and type two lines of text in the rich text editor :

![image](https://user-images.githubusercontent.com/2527227/30053599-a8cbaab4-9229-11e7-8226-8c0b84f19b2d.png)

I check the source, and I see what I excpect to see :

![image](https://user-images.githubusercontent.com/2527227/30053613-b8208f7a-9229-11e7-9217-04d04e8221c3.png)

I save the page, and troubles begin : now in the wysiwyg editor I see and extra blank line :

![image](https://user-images.githubusercontent.com/2527227/30053639-cd756cd8-9229-11e7-890e-a96530640abd.png)

and the source looks like this :

![image](https://user-images.githubusercontent.com/2527227/30053658-d9e9ad26-9229-11e7-870f-0f0da62c5c86.png)

I used Chrome's dev tools to see what is sent to Typo3 from the client, and unless I'm mistaken, it seems like the clients sends what it is supposed to send :

```
Content-Disposition: form-data; name="data[tt_content][13][tx_templavoilaplus_flex][data][sDEF][lDEF][field_caracteristiques][vDEF]"

<p>This is line 1</p>

<p>This is line 2</p>
```

Rich text elements work fine when they are not inside an FCE - for example, a Regular Text Element is save correctly.

Did I do something wrong or is there a problem with Rich Text Elements inside FCEs ?

Anything I can do to help (more tests, try patches, etc ...) let me know.

Typo3 8.7.4 and CKEditor Rich Text Editor (rte_ckeditor) 8.7.4

**Comment by opi99** [comment]
Hmmm, no, I've the same issue but thought it is an issue with the new ck editor. But if this only happens with FCEs and not with normal elements ... I should take a look into my source. :)

**Comment by ymauray** [comment]
If you give me some pointers, I can start digging and see if I spot something.

**Comment by opi99** [comment]
Hmmm, I've no spot, but following information. The FCE flexform textfield is like a normal TCA textfield with following default configuration:

```
<config type="array">
        <type>text</type>
        <cols>48</cols>
        <rows>5</rows>
        <softref>typolink_tag,images,email[subst],url</softref>
</config>
<defaultExtras>richtext:rte_transform[flag=rte_enabled|mode=ts_css]</defaultExtras>
```

**Comment by opi99** [comment]
Reducing to this minimum also leads to the issue:

```
					<config type="array">
						<type>text</type>
					</config>
					<defaultExtras>richtext</defaultExtras>
```

**Comment by opi99** [comment]
*lol* Ok found it, fix (Updating migration job) hopefully tomorrow.

The field config in FlexForm TCA needs to be (if you like to try yourself):
```
<TCEforms type="array">
        <label>Content</label>
        <config type="array">
                <type>text</type>
                <enableRichtext>1</enableRichtext>
        </config>
</TCEforms>
```

While the new Backend Form migrates this into the cached TCA, FlexForms aren't cached. Ando so saving this through the DataHandler leads to an field config without migration, so RTE_transform_db is never called.

While in direction rte an empty line is added it isn't removed into the other direction.
If already an empty line exists it will be filled with <p>&nbsp</p> (and one empty line defore and after). This leeads to more&more blank lines.
Migrating TCA Config correctly resolves the issue ... but it doesn't fix this damn fucking handling of adding/replacing/removing new lines for nothing.

**Comment by ymauray** [comment]
I changed the config and yes, it works ! Thanks, you rock ! 👍

**Comment by opi99** [comment]
Reference: https://forge.typo3.org/issues/72856
