### ISSUE TITLE
Allow assigning FCEs to different Tabs in NewContentElementWizard

### ISSUE THREAD

**Issue by jpmschuler** [pluspol-interactive/templavoilaplus#128]
We have `mod.wizards.newContentElement.wizardItems.fce.show = 13,36` to limit the FCEs available in the NewContentElementWizard (NCEW) - however we can't change the Tab they are shown in, because the internal function fills the complete tab, as it parses the special array-key "fce".

If one would add a similar parser for elements (instead of tab) of the pattern "fce_<uid>" using the existing functionality we could move the elements to whatever tab we like, so instead of defining a complete element manually like: 

    mod.wizards.newContentElement.wizardItems.responsive {
	header = responsive FCEs
	elements {
		fce_76 {
          icon =...
          description =...
          params = &defVals[tt_content][CType]=templavoilaplus_pi1&defVals[tt_content][tx_templavoilaplus_ds]=<mypath_to_static_DS_of_FCE>/<my_ds>.xml&defVals[tt_content][tx_templavoilaplus_to]=<uid_of_fces_to>
         }
	}
    }

just adding an "empty" `mod.wizards.newContentElement.wizardItems.<mytab>.fce_76` should make the additional parser add all necessary properties unless they are already set.

(Idea from Slack-Discussion with @frankg01)

**Comment by jpmschuler** [comment]
As in my projects I now override a whole lot of wizardItems and tabs, I came to rethink this issue. If it should stick with this type perhaps a more TV+ bound pattern could help reduce conflicts, e.g. `templavoilaplus_fce_76`. 

Still wonder if that should be postponed. It is a wonderful thing for integrators, but as the manual thing works flawlessly and allows even more stuff (like adding a meaningful title for the content element) we should perhaps just document this better.

**Comment by opi99** [comment]
After more then 3 years, this is now done in TV+ v8 code base. :-)
But it needs someone who could write a documentation about this.

In short, look into the demo extension https://github.com/extrameile/em_tvplus_theme_demo
A bit longer:

You need in your theme extension inside the Configuration/TVP folder a file called NewContentElementWizard.php which returns an array with the field "overwrites" that includes all changes you wishes to change.

Implemented is unsetting, moving before/after of tab. It also includes Move command for NewContentElementConfigurations. Hold in mind, TV+ converts the NewContentElementWizard configuration (tabs configuration and elements configuration in one array) to a multi dimensional array (the tabs configuration has the element configuration inside the field contentElements).

All in all here the example configuration array

```
return [
    'overwrites' => [
        'common' => [
            // after/before see TYPO3\CMS\Core\Service\DependencyOrderingService
            'after' => ['fce'],
            'move' => [
                'common_header' => ['tab' => 'interactive', 'before' => 'interactive_accordion']
            ],
        ],
        'data' => [
            'unset' => true,
        ],
        'fce' => [
            'move' => [
                'fce_EM\TVP\Theme\Demo\Fce\Mapping:Card.tvp.yaml' => ['tab' => 'common', 'before' => ['common_bullets', 'common_image']],
                'fce_EM\TVP\Theme\Demo\Fce\Mapping:TextboxWithLink.tvp.yaml' => ['tab' => 'common', 'before' => ['fce_EM\TVP\Theme\Demo\Fce\Mapping:Card.tvp.yaml']],
            ],
        ],
    ],
];
```
