### ISSUE TITLE
Not possible to mapping the template from filelist 

### ISSUE THREAD

**Issue by TYPO3plusi** [pluspol-interactive/templavoilaplus#131]
In 7.6.x it works, in 8.7.x not.

**Comment by opi99** [comment]
Can you add a screenshot of 7.6 where it works?

**Comment by TYPO3plusi** [comment]
Sure, here is a screenshot:
https://imgur.com/a/MKhNj

**Comment by opi99** [comment]
Ok, thx, then I'll close this issue as duplicate of #75
