### ISSUE TITLE
Define a constant in main template and use it in a flexible CE

### ISSUE THREAD

**Issue by joerg2201** [pluspol-interactive/templavoilaplus#132]
Hello,

with TemplaVoila! it was possible to define a constant in a template and use this constant in a felixible content element (TemplaVoilà Template Mapping):

In the setup of the main template:
#Constant
plugin.tx_templavoilaplus_pi1.TSconst.readmore = read more

In the data processing text area:
......
70 = TEXT
70.data = register:tx_templavoilaplus_pi1.parentRec.uid
70.if.isTrue.data = field:field_content_text_more
70.wrap = {$TSconst.readmore}</a></span><br /><br /><div class="invisible">|</div>

This is not working anymore.
Any suggestions?

Cheers
Jörg

**Comment by opi99** [comment]
Is it an old configuration which you try to use with new TV+?

I didn't changed something in this part, so should work as before. Looked shortly in the code and didn't found something looking wrong.

I don't have such a setup and I don't understand not fully the original documentation https://docs.typo3.org/typo3cms/extensions/templavoilaplus/T3datastructureExtensions/Introduction/Index.html :-( 

Can you explain a bit more detailed, what I need to set where?

**Comment by opi99** [comment]
Closing as invalid as I got no response here.
If you still have issues contact me on slack channel.
