### ISSUE TITLE
Header is not rendered

### ISSUE THREAD

**Issue by deividasgab** [pluspol-interactive/templavoilaplus#133]
After migrating from templavoila to templavoila plus I cannot get the header be displayed.

![templavoilaplus1](https://user-images.githubusercontent.com/31312446/31164047-0aa04ee0-a8ee-11e7-9f6f-0c0644e29aaf.PNG)

The part marked red are not displayed.

I use css_styled_content which is included in template.

**Comment by opi99** [comment]
Hi,

as already written in slack channel by Peter Schuler, the header isn't outputted by default. It seams you had TypoScript globally or inside the data structures which did this job. You need to migrate this by hand. Maybe you can post me one of your data structures XML in slack and I'll look into it.
