### ISSUE TITLE
BackendLayoutController::getAvailableLanguages works wrong if static_info_tables isn't installed

### ISSUE THREAD

**Issue by typecat** [pluspol-interactive/templavoilaplus#143]
If static_info_tables isn't installed Ppi\TemplaVoilaPlus\Controller\BackendLayoutController::getAvailableLanguages unsets the additional languages in the $output array.

The issue starts on line 3102:
`$staticLangRow = BackendUtility::getRecord('static_languages', $row['static_lang_isocode'], 'lg_iso_2');`
`if ($staticLangRow['lg_iso_2']) {`
`		$output[$row['uid']]['ISOcode'] = $staticLangRow['lg_iso_2'];`
`}`
Because $staticLangRow receives null here, $output[$row['uid']]['ISOcode'] isn't set and affects line 3111:
`if ($onlyIsoCoded && !$output[$row['uid']]['ISOcode']) {`
`	unset($output[$row['uid']]);`
`}`

As a result the translations tab doesn't appear although additional languages are set up. Thanks @opi99 for helping me find the cause.

TYPO3 7.6.23
templavoilaplus 7.2.0

**Comment by opi99** [comment]
This issue isn't fixed completely, there are 3 positions with (more or less) same code?

**Comment by opi99** [comment]
As the patch is big and strives over 2 other places, and changes API a bit, I set this back for 7.3.0 release.
