### ISSUE TITLE
Editing hidden elements returns "Unexpected Result: uid xxx FROM tt_content"

### ISSUE THREAD

**Issue by rareshluk** [pluspol-interactive/templavoilaplus#146]
When trying to edit a hidden FCE in Page or List view, the form crashes with the exception:
Unexpected Result: uid xxx FROM tt_content 
Ppi\TemplaVoilaPlus\Exception\DataStructureException thrown in file
/httpdocs/typo3conf/ext/templavoilaplus/Classes/Form/Container/FlexFormElementContainer.php in line 104.

Running TYPO3 8.7.8, TemplaVoila Plus 7.2.0

Debugging a bit, I noticed that the where clause for the select query includes a hidden=0 condition:
 [sql:Doctrine\DBAL\Query\QueryBuilder:private] => SELECT * FROM `tt_content` WHERE (`uid` = :dcValue1) AND ((`tt_content`.`deleted` = 0) AND (`tt_content`.`hidden` = 0) AND (`tt_content`.`starttime` <= 1510651800) AND ((`tt_content`.`endtime` = 0) OR (`tt_content`.`endtime` > 1510651800)))

(I would say that in BE mode only the deleted=0 makes sense - all the other shouldn't prevent the backend user from seeing/editing the element)

Any hints on fixing this?
Thanks!

**Comment by opi99** [comment]
Tested it with TYPO3 7.6.23 and TV+ 7.2.0 didn't lead me to an crash.

**Comment by opi99** [comment]
Tested now with TYPO3 8.7.8 and TV+ 7.2.0 also didn't crash and worked as it should.

**Comment by opi99** [comment]
Also there is no DataStructureException thrown inside FlexFormElementContainer, the only position where such an exception can be thrown is while reading XML of a DataStructure.

So something is odd on your system.

**Comment by rareshluk** [comment]
Hmm, in this case it must be the DataStructure that causes it.
It is a four col element, where the user can add inline imagetext, or video elements.
I will attach here the xml file. Do you see anything in there that might cause it?
[test_DS.txt](https://github.com/pluspol-interactive/templavoilaplus/files/1473856/test_DS.txt)

**Comment by opi99** [comment]
The issue comes from https://github.com/pluspol-interactive/templavoilaplus/pull/140
so you may speak up there as the code is not mine.

**Comment by opi99** [comment]
So you patched your TV+ 7.2.0

**Comment by rareshluk** [comment]
I will test the patch right now, thanks!

**Comment by opi99** [comment]
No, it seams you hav TV+ and installed this patch.

**Comment by rareshluk** [comment]
Sorry, Yes, indeed,

**Comment by rareshluk** [comment]
I needed the patch for fixing the issue #109

**Comment by opi99** [comment]
Yes but this seams broken then, so I'll close this issue.
