### ISSUE TITLE
v8: Copy page with Ds/To configuration failes with error

### ISSUE THREAD

**Issue by opi99** [pluspol-interactive/templavoilaplus#160]
`Incomplete "record" based identifier: {"type":"record","tableName":"pages","uid":0,"fieldName":"tx_templavoilaplus_ds"}`

**Comment by opi99** [comment]
Issue with the "uid" field which is 0.

**Comment by opi99** [comment]
@rareshluk

Do you have DataStructure in files?

**Comment by rareshluk** [comment]
Yes

**Comment by opi99** [comment]
Ok, will try my best, fixing this ... but luckily I can reproduce it.

**Comment by rareshluk** [comment]
@opi99 Hi , Any news on this issue? Did you manage to reproduce the bug?
Thanks!

**Comment by opi99** [comment]
As I already wrote, I can reproduce the issue.
I may come tomorrow to this issue and will fix it.

**Comment by rareshluk** [comment]
That would be great!
I thought you were hoping to be able to reproduce it when you wrote "luckily" :)
Thanks again for your work!

**Comment by azeef** [comment]
@opi99 Do we have a patch for this yet ?

**Comment by opi99** [comment]
@azeef No patch available yet. Customer projects is in "Pause" mode as something else is more importend.

**Comment by opi99** [comment]
It's also not possible to create new pages, without the error message.

**Comment by opi99** [comment]
But not always? :-?

**Comment by opi99** [comment]
Tested also recursive page copy which worked
