### ISSUE TITLE
Add label to new section item

### ISSUE THREAD

**Issue by danielkoch** [pluspol-interactive/templavoilaplus#163]
I'm using templavoilaplus in version 7.2.1.
Here I create an FCE with a "Selection of elements" (SC) for adding different "Container of elements" (CO) to bring the possibility of different content type variants.
Can I add a label beside the icon/button that shows the name of the CO item?
<img width="336" alt="fce-new-item" src="https://user-images.githubusercontent.com/142055/36642824-6696fc94-1a45-11e8-8cc2-2b6742151bf5.png">

I migrated from `templavoila` and here the label from the CO was used:
```
<tx_templavoila type="array">
	<title>My label</title>
	<eType>input</eType>
	<TypoScript></TypoScript>
	<proc type="array">
		<int>0</int>
		<HSC>0</HSC>
		<stdWrap></stdWrap>
	</proc>
	<preview></preview>
</tx_templavoila>
```

**Comment by opi99** [comment]
Checking issue #130 could you move the title accordingly to the same level as the <tx_templavoilaplus> definition? (Btw: tx_templavoila should be tx_templavoilaplus).

Does it help already? If not, I need to check it in the next days.

**Comment by danielkoch** [comment]
Yes, it works. But the `<title>`must copied because otherwise the maintainable **Title** used by the GUI
<img width="313" alt="gui-title" src="https://user-images.githubusercontent.com/142055/36714526-e300f73c-1b92-11e8-964d-d3aea0dd28f4.png">
is empty.

**Comment by opi99** [comment]
Ok, fine ... then I would close this issue as duplicate of #130 and will fix it there. Ok?

**Comment by danielkoch** [comment]
Sure. Thanks for your work!
