### ISSUE TITLE
Installation 7.6 lts successfull, conversion successfull, but Website shows no content!

### ISSUE THREAD

**Issue by itsolon** [pluspol-interactive/templavoilaplus#166]
Hi, thank you for the second spring for templavoila(plus)
i installed the Extension and ran the update scripts, but the Website does not Show any Content.
are there additional steps needed for showing the Website?
the Website Shows no Content not even the logo is shown
i think i have to Switch off the parallel used Extensions template?
do i have to map something inside?
or are there any tricks i have to do for showing the
(inside there is an typo3 extenison template which is enabled, templavoila is disabled)

**Comment by opi99** [comment]
Hi,

this sounds more like you forgot to replace the call to templavoilaplus in your typoscripts.
Also for help please use the the slack channel https://typo3.slack.com/messages/templavoilaplus

Hope this helps you, greetings Alex//

**Comment by itsolon** [comment]
Thank you very much for your Reply.
I have successfully renamed every tx_templavoila wo tx_templavoilaplus i found with grep -r ‚tx_templavoila‘ (upper Apostroph)
In 6 template XML files ds/page and ds/fce

And one typoscript Setup.ts with following

But nothing is shown i am not familiar with templavoila
And have seen some Videos where they map with right click
This seems to Show the Website inside with marks but with or without such mappings .. White page.

#print = PAGE
#print {
#    bodyTag = <body onload="window.print();">
#    typeNum = 98
#    includeCSS {
#        print = /fileadmin/templates/css/print.css
#        print.media = print
#    }
#    10 = TEXT
#    10.value = <a href="javascript:window.print();>Drucken</a>
#    10.wrap = <div id="printToolbar"><div id="printPrintLink">|</div>
#    20 = TEXT
#    20.value = <a href="javascript:window.close();>Schlie&szlig;en</a>
#    20.wrap = <div id="printCloseLink">|</div></div>
#
#    40 = HTML
#    40.value = <hr />
#    49 = HTML
#    49.value = <div id="printContent">
#    50 = USER
#    50.userFunc = tx_templavoilaplus_pi1->main_page
#    51 = HTML
#    51.value = </div><div class="clear"></div>
#}


Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Alexander Opitz <notifications@github.com>
Gesendet: Monday, March 19, 2018 2:18:24 PM
An: pluspol-interactive/templavoilaplus
Cc: Markus Peikert; Author
Betreff: Re: [pluspol-interactive/templavoilaplus] Installation 7.6 lts successfull, conversion successfull, but Website shows no content! (#166)


Hi,

this sounds more like you forgot to replace the call to templavoilaplus in your typoscripts.
Also for help please use the the slack channel https://typo3.slack.com/messages/templavoilaplus<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftypo3.slack.com%2Fmessages%2Ftemplavoilaplus&data=02%7C01%7C%7Ca96dcd99042a4a57b77508d58d9be68a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636570623087559555&sdata=oeg2j3RJD63S55RYHlm%2FSIPxPue8txXwQUblbsRquBY%3D&reserved=0>

Hope this helps you, greetings Alex//

**Comment by opi99** [comment]
Look at point 15 in the manual: https://docs.typo3.org/typo3cms/extensions/templavoilaplus/Migration/Index.html

You should change your `50.userFunc` accordingly.

**Comment by itsolon** [comment]
I see. But this lines are commented out with #
I do not find any other „page object Definition“
Can you tell me where to search?
Some path?
Because any Manual
https://docs.typo3.org/typo3cms/TyposcriptIn45MinutesTutorial/TypoScriptOverview/FirstSteps/Index.html
i can find they do not speak about path where i can find those Definition files

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Alexander Opitz <notifications@github.com>
Gesendet: Monday, March 19, 2018 2:40:47 PM
An: pluspol-interactive/templavoilaplus
Cc: Markus Peikert; Author
Betreff: Re: [pluspol-interactive/templavoilaplus] Installation 7.6 lts successfull, conversion successfull, but Website shows no content! (#166)


Look at point 15 in the manual: https://docs.typo3.org/typo3cms/extensions/templavoilaplus/Migration/Index.html<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.typo3.org%2Ftypo3cms%2Fextensions%2Ftemplavoilaplus%2FMigration%2FIndex.html&data=02%7C01%7C%7C72fd5a006b464d45545908d58d9f0689%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636570636510291660&sdata=x91PaqwAf8RmGcdpHDLfapKgHrzLi3ROJQcVhPWxkAM%3D&reserved=0>

You should change your 50.userFunc accordingly.

**Comment by opi99** [comment]
If this code is commented out, it seams you have no PAGE object.
Without PAGE object you won't have output.

**Comment by itsolon** [comment]
Okay thank you for your answer
In short
„ gab es Projekte wo man templavoila nutze und dann doch in den template kein „page objetzt „ gesetzt“ hat weil man es selber gemacht hat?

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Alexander Opitz <notifications@github.com>
Gesendet: Tuesday, March 20, 2018 12:35:27 PM
An: pluspol-interactive/templavoilaplus
Cc: Markus Peikert; Author
Betreff: Re: [pluspol-interactive/templavoilaplus] Installation 7.6 lts successfull, conversion successfull, but Website shows no content! (#166)


If this code is commented out, it seams you have no PAGE object.
Without PAGE object you won't have output.

**Comment by opi99** [comment]
Im Template gibt es eh kein PAGE objekt, sondern im TypoScript.
Ohne PAGE Objekt geht es nur, wenn man das Rendering irgendwie andersweitig angestoßen hat.

**Comment by opi99** [comment]
Closing this issue as it has no response anymore.
