### ISSUE TITLE
make extension TYPO3 composer mode compatible

### ISSUE THREAD

**Issue by jpmschuler** [pluspol-interactive/templavoilaplus#168]
(The extension is currently not on Packagist, this should be improved, after this issue is fixed)

If one tries to install the extension with an repository
`{
      "type": "vcs",
      "url": "https://github.com/jpmschuler/templavoilaplus/"
    }`
and e.g.
`"templavoilaplus/templavoilaplus": "^7.0",`
it results in composer creating the folder `typo3conf/ext/templavoila`, instead of `typo3conf/ext/templavoilaplus`.

At least in my install this corrupts the installation and creates different errors everywhere.

Currently no idea where to look for a fix, just wanted to document it first.

**Comment by jpmschuler** [comment]
Wonderful then it's again composer cache :-/

**Comment by jpmschuler** [comment]
@christian-fries thx for the input.
For further reference: it was a working 7LTS install with tv+ and without tv in migration to 7LTS@composer. Some old composer.lock and a corrupted composer cache seems to have been the problem, as so often...

**Comment by opi99** [comment]
@jpmschuler This may be the renaming thing, the old git url was templavoila.git
Thanks christian for digging in.

So it should be save to add this to packagist?

**Comment by jpmschuler** [comment]
Think so, currently using path instead of vcs due to a local patch, but my configuration was broken in multiple ways so I would believe in christian. Opened #170.
