### ISSUE TITLE
FormFlexAjaxController does not have a method fetchDataAction

### ISSUE THREAD

**Issue by christian-fries** [pluspol-interactive/templavoilaplus#169]
When editing backend groups in TYPO3 8.7.12 with current master, `category_perms` doesn't show any categories because the networt call to `/typo3/index.php?ajaxID=/ajax/record/tree/fetchData&ajaxToken=12058d1d1645a377d10ec26ba75f2097db5ce0a9&tableName=be_groups&fieldName=category_perms&uid=1&recordTypeValue=0&dataStructureIdentifier=&flexFormSheetName=&flexFormFieldName=&flexFormContainerName=&flexFormContainerIdentifier=&flexFormContainerFieldName=&flexFormSectionContainerIsNew=&command=edit` fails with this error message:
`Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Ppi\TemplaVoilaPlus\Form\Controller\FormFlexAjaxController' does not have a method 'fetchDataAction' in /var/www/website/vendor/typo3/cms/typo3/sysext/backend/Classes/Http/RouteDispatcher.php on line 54`

**Comment by christian-fries** [comment]
Actually all category trees do not show categories.

When I remove the duplicate key `record_tree_data`(L31 - L34) in `Configuration/Backend/AjaxRoutes.php`, category trees are working again but I don't know what impact that change has on other parts of the system.

**Comment by opi99** [comment]
Oh, this seams a C&P error while patching #109 
Thanks for the hint.
