### ISSUE TITLE
Add project to packagist for better composer discovery and maintainability

### ISSUE THREAD

**Issue by jpmschuler** [pluspol-interactive/templavoilaplus#170]
https://github.com/pluspol-interactive/templavoilaplus.git should be added as templavoila/templavoila on [packagist](https://packagist.org). The setup ist done in minutes. If github is used like here and the hooks/integration is done like the packagist setup recommends, it is a one-time-setup, with no additional steps ever as everything is updated via post-commit-hooks (or something similar).

**Comment by opi99** [comment]
I added it today as https://packagist.org/packages/templavoilaplus/templavoilaplus ... can you test if it works?

**Comment by jpmschuler** [comment]
works flawlessly, thx
```
$ composer req templavoilaplus/templavoilaplus
Using version ^7.2 for templavoilaplus/templavoilaplus  
  - Installing templavoilaplus/templavoilaplus (7.2.3): Downloading (100%)
