### ISSUE TITLE
Prevent admin status from dropping TCEFORM.pages.tx_templavoilaplus_to.removeItems

### ISSUE THREAD

**Issue by jpmschuler** [pluspol-interactive/templavoilaplus#171]
The current implementation allows TCEFORM.pages.tx_templavoilaplus_to.removeItems only for non-Admin users. 
`Ppi\TemplaVoilaPlus\Domain\Model\Template
[...]
 public function isPermittedForUser($parentRow = array(), $removeItems = array())
    {
        if (TemplaVoilaUtility::getBackendUser()->isAdmin()) {
            return true;
        }
[...]
`

I'd suggest removing this special lines, because of three reasons:
- This is a behaviour uncommon for TYPO3 and stupid integrators might stumble upon it.
- removeItems is defined in pageTSconfig, pageTSconfig has [a condition for "if admin"](https://docs.typo3.org/typo3cms/TSconfigReference/Conditions/Index.html#adminuser) if necessary
- there is a use case where an admin wants to remove these icons for his view as well, e.g. hundreds of templates for pages/fce and they are bound to specific page branches or domains

**Comment by opi99** [comment]
Hehe, ok ... sounds reasonable, but would add this as a plugin option. Ok?

**Comment by jpmschuler** [comment]
I'd consider it a simple bug and not intended or used behaviour, but I get your point that it might be considered a breaking change.

**Comment by opi99** [comment]
Should I do same for 
`Ppi\TemplaVoilaPlus\Domain\Model\DataStructure::isPermittedForUser`
`Ppi\TemplaVoilaPlus\Domain\Model\StaticDataStructure::isPermittedForUser`
??

**Comment by jpmschuler** [comment]
As `basic.enable.selectDataStructure` is deprecated anyways, I won't see a need for that, but perhaps I'm forgetting something

**Comment by opi99** [comment]
It's deprecated for 8.x releases and this do not change anything here ;-)
