### ISSUE TITLE
PHP 7.2 - count warning

### ISSUE THREAD

**Issue by Juerg-E** [pluspol-interactive/templavoilaplus#172]
PHP Warning: count(): Parameter must be an array or an object that implements Countable ...
See: http://php.net/manual/de/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types
Similar bug and resolve see "https://forge.typo3.org/issues/83345"

**Comment by opi99** [comment]
The big question is ... where did the warning occured?
I checked TV+ but maybe I missed one.

**Comment by Juerg-E** [comment]
Got the warnings after save a content element [cid:66849a35-e2b6-4622-8b22-adf8a8c27d48]

Can't tell you more because I switched back to PHP 7.0 - waiting for 9LTS.


Greetings

Jürg


________________________________
Von: Alexander Opitz <notifications@github.com>
Gesendet: Montag, 16. April 2018 14:25
An: pluspol-interactive/templavoilaplus
Cc: Juerg-E; Author
Betreff: Re: [pluspol-interactive/templavoilaplus] PHP 7.2 - count warning (#172)


The big question is ... where did the warning occured?
I checked TV+ but maybe I missed one.

**Comment by opi99** [comment]
So closing this issue as invalid
