### ISSUE TITLE
BEmodule: Not used elements doesn't scroll if too long

### ISSUE THREAD

**Issue by jpmschuler** [pluspol-interactive/templavoilaplus#184]
I'm on a page in TV+ BEmodule which is about 1.5 screens long, thus having a scrollbar. I open the "Not used elements" tabs, which is about 1.25 screens long. Scrolling down will scroll the Page content, not the Tab content, thus I never see the lower few entries.

Isn't that separation in top and main core functionality?

Safari 11.1.1, OSX 10.13.5, TYPO3 7LTS, TV+ 7.2.3

**Comment by opi99** [comment]
It's a partly misused core functionality. So you have so much "unused" elements that the list is longer then the screen?
Ok, this needs some changes for the content inside the tab, maybe need to set an max-height and overflow:scroll into css.

**Comment by jpmschuler** [comment]
Yep, so many unused elements (15-20 I think). Just a small thing but I agree that 2 lines of css might be enough.
