### ISSUE TITLE
missing link to the manual

### ISSUE THREAD

**Issue by franzholz** [pluspol-interactive/templavoilaplus#191]
The TYPO3 page 
https://extensions.typo3.org/extension/templavoilaplus/
does not have any link to the online manual.
The external manual is here:

https://docs.typo3.org/typo3cms/extensions/templavoilaplus/

You must use Google to find the online manual.

**Comment by opi99** [comment]
This is not the External Manual ... this is the Extension Manual.

But something in TER is broken and so the link isn't shown anymore (around releasing 7.2.3), as this is autogenerated information I can't configure this in the TER backend.

Will close this, as it isn't a bug inside TV+, but I have this issue on my list, to check TER documentation again (for changes) and contact TER Team about this.
