### ISSUE TITLE
v7.2.4: Keep title values in mapping module when migrating existing titles to new datastructure model

### ISSUE THREAD

**Issue by fgerards** [pluspol-interactive/templavoilaplus#192]
The upgrade wizard in Extension Manager moves "title" Attributes in the datastructure, thus the field titles in the mapping module get lost. 
Solution: Don't move, but copy the title nodes.

#130

**Comment by opi99** [comment]
Thanks for reporting, but I don't like to copy the data to multiple places, but instead fixing the mapping tool.
