### ISSUE TITLE
8LTS: Header Mapping for Page TemplatObjects is ignored

### ISSUE THREAD

**Issue by jpmschuler** [pluspol-interactive/templavoilaplus#197]
In 7LTS I used "Header Set" during TemplateObject mapping to set my body class (to differ between has sidebar and has no sidebar), e.g.:
<img width="471" alt="bildschirmfoto 2018-08-11 um 10 34 04" src="https://user-images.githubusercontent.com/12411176/43990022-83a0a3ba-9d55-11e8-8e38-c8f0098c8f2a.png">
This resulted in the body class being set as `<body class="clearfix layout1">`

After updating to 8LTS the body class is empty now, instead of having the classes set.

**Comment by opi99** [comment]
See https://forge.typo3.org/issues/77184
defaultBodyTag is removed with the comment
```
For the property :php:`defaultBodyTag` the according TypoScript settings can be used to override the
body tag or the page title.
```
