### ISSUE TITLE
Make TmplObj.previewicon a file reference, instead of a file upload field.

### ISSUE THREAD

**Issue by jpmschuler** [pluspol-interactive/templavoilaplus#203]
Currently the field `tx_templavoilaplus_tmplobj.previewicon` is a file upload field while `belayout`and `fileref`have the option to reference the file. I'd suggest making all of them alike, as typically all of them would be often in a template folder/extension. And could thus be replaced via a deployment.

I know that this is not urgent and would need a migration wizard as well. 
(Nevertheless this would make it one step easier so supply the complete records (and in the end the mapping using an extension).

**Comment by opi99** [comment]
While checking your request, `tx_templavoilaplus_datastructure.previewicon` also have an upload field configuration. Should we transform this same alike?

**Comment by jpmschuler** [comment]
DB-based datastructure is deprecated. 
Additionally the default is that you can't select the datastructures but only the TObj, so i don't know where this should be displayed except for the admin/integrator during configuration.
 
So I'd say it isn't worth the effort. But I get it might be easier to have similar configuration everywhere meanwhile.

**Comment by opi99** [comment]
Ok, its not really displayed anywhere.
This will lead to one more field which isn't controllable by sanitizer checks if the content is correct. (As we do not have the "theme extension" path configuration yet.) ... *hmmm*

**Comment by opi99** [comment]
I would like to close this one.
1) It's a feature for the 7.x line of TV+ which I like to have only in maintenance mode yet
2) In the 8.x line we will have a complete new way and this isn't needed anymore (hopefully)
Is it ok for you?

**Comment by jpmschuler** [comment]
Of course that's fine
