### ISSUE TITLE
file reference on Rich text editor for bodytext not working

### ISSUE THREAD

**Issue by drogu02** [pluspol-interactive/templavoilaplus#211]
![image](https://user-images.githubusercontent.com/43148349/45314105-dbf8ab00-b4fe-11e8-90d3-0ecbaab69ff7.png)
![image](https://user-images.githubusercontent.com/43148349/45314171-0c404980-b4ff-11e8-88c2-e939c5cbdee2.png)
When I create a file link, the file have no reference
![image](https://user-images.githubusercontent.com/43148349/45314331-6ccf8680-b4ff-11e8-8b21-ae7d7011d9ef.png)

**Comment by opi99** [comment]
Hi,

as TV+ haven't todo with the softref things ... does it work on non-FlexForm elements?
And which TV+ and TYPO3 Version do you use?

**Comment by drogu02** [comment]
Yes it work with normal links.
Typo3 version : 8.7.19 
TV+ version : 7.2.3

**Comment by opi99** [comment]
Do you eventually know if this works with FlexForms on non-TV installations?
As we only pass this and do not work with softref, I feel a bit like "This is not our issue" ;-)

**Comment by drogu02** [comment]
I don't really know how to test it unfortunately :(

**Comment by opi99** [comment]
Hi, does this issue still exists?

**Comment by opi99** [comment]
No response, so closing this issue.
