### ISSUE TITLE
No preview if language is -1 

### ISSUE THREAD

**Issue by oliverbeck** [pluspol-interactive/templavoilaplus#214]
I have some elements with sys_language_uid = -1 (All). In this case I don't see any preview of the fields. I would like to show preview of the default language.

**Comment by opi99** [comment]
Preview works for me on element with sys_language_uid = -1
![screenshot_20181101_152659](https://user-images.githubusercontent.com/1672061/47858565-ab413d80-ddec-11e8-828e-d0a2cbcbf2e9.png)

**Comment by opi99** [comment]
Closing as no response was given.
