### ISSUE TITLE
v8/9: custom RTE configuration is not loaded in FCEs

### ISSUE THREAD

**Issue by fgerards** [pluspol-interactive/templavoilaplus#224]
TcaFlexProcess class of templavoilaplus didnt integrate the latest bugfixes in the core class it is replacing, see attached patch. effectivePid is needed for the configuration of an RTE field to be loaded in TYPO3 8.5+
[patches_templavoilaplus_https___forge_typo3_org_issues_83809_patches_templavoilaplus_https.txt](https://github.com/pluspol-interactive/templavoilaplus/files/2786698/patches_templavoilaplus_https___forge_typo3_org_issues_83809_patches_templavoilaplus_https.txt)

**Comment by opi99** [comment]
Original issue: https://forge.typo3.org/issues/83809

**Comment by opi99** [comment]
Should be fixed.
