### ISSUE TITLE
Closed bodytag in template

### ISSUE THREAD

**Issue by typo3plus** [pluspol-interactive/templavoilaplus#225]
I have a closed bodytag in Templavoila, it cant come from the template. Please look@it opi99

Thanks for your great Extension and TemplaVoila Support

**Comment by opi99** [comment]
Oh, can I have less information please? I like to dig into the dark.

**Comment by typo3plus** [comment]
Hello Opi99,
I have a </body> endtag in TemplaVoilaPlus, but there is no body endtag in template @ this position.

![entag](https://user-images.githubusercontent.com/47587419/52710959-e842d180-2f90-11e9-9af4-465bdee6e4a7.jpg)

**Comment by opi99** [comment]
So from screenshot, as I see, you are inside the mapping tool? Also, a good information would be
version of TYPO3, version of TemplaVoilà! Plus, was it migrated? Was the issue present before?

**Comment by typo3plus** [comment]
Oh sry, opi99, that was a small template misstake from me, i had to delete the menu,
Really sry, i hope you are not angry.

Thanks for your great support and continue your great extension.

**Comment by opi99** [comment]
So I can close the issue?

**Comment by typo3plus** [comment]
yes, wish you a good day opi99
