### ISSUE TITLE
Error in frontend when a page has no page template set in live workspace, but in another workspace

### ISSUE THREAD

**Issue by fgerards** [pluspol-interactive/templavoilaplus#226]
If a page has no page-template in live-workspace but has assigned one in a workspace, a frontend error is triggered when viewing the live-workspace version of the page, that has no page template set.

TYPO3 8.7 + TV+ latest

**Comment by opi99** [comment]
BE Error on page in WS:
/vagrant/webapp/htdocs/public/typo3_src/typo3/sysext/core/Classes/Configuration/FlexForm/FlexFormTools.php in line 719

I don't have issues in FE. Are there other ways to trigger? And can you post me the FE error?
