### ISSUE TITLE
PageModule: Deleting translated item directly results in exception

### ISSUE THREAD

**Issue by jpmschuler** [pluspol-interactive/templavoilaplus#227]
stable TV 7.3.0.1

In PageModule with language fallback deleting a tt_content-translation directly from context menu creates exception:
![bildschirmfoto 2019-02-22 um 11 55 29](https://user-images.githubusercontent.com/12411176/53238215-00a1a300-3699-11e9-9763-73b63cf06e46.png)

Oops, an error occurred!
Argument 4 passed to Ppi\TemplaVoilaPlus\Configuration\FlexForm\FlexFormTools8::getDataStructureIdentifier() must be of the type array, null given, called in /typo3conf/ext/templavoilaplus/Classes/Service/ApiService.php on line 1384

**Comment by jpmschuler** [comment]
![bildschirmfoto 2019-02-22 um 12 07 16](https://user-images.githubusercontent.com/12411176/53238922-ea94e200-369a-11e9-8381-0e3ed51f6fa9.png)
Same with "not used elements" tab above.

However it seems to be related to a broken import - the respective tt_content element doesn't show up in list view as well (although the db row looks fine). 

I don't get the error message though and thus leave this open for your consideration instead of closing it due to "local install issues".

**Comment by opi99** [comment]
Hi,

can you send a backtrace for ApiService::ds_getExpandedDataStructure ? The $row seams already empty at this point.

**Comment by opi99** [comment]
Closing after feedback on slack ... ATM not reproducible.
