### ISSUE TITLE
Check if user selected a template to convert (value is array or countable PHP7.2)

### ISSUE THREAD

**Issue by hrdyy** [pluspol-interactive/templavoilaplus#228]
https://github.com/pluspol-interactive/templavoilaplus/blob/829cd598df654e001a6df0ffc9a746960f89d2dd/Classes/Controller/Update/StaticDataUpdateController.php#L191

**Comment by opi99** [comment]
Hi,

could you tell me, what did you do while update to static data?

**Comment by opi99** [comment]
It seams you didn't selected any template to convert?

**Comment by hrdyy** [comment]
I Upgrade an Typo3 6 system to Typo3 9, the old system uses static Templates in templavoila after switching to plus, i move through the wizards and there i found These Problem.

**Comment by opi99** [comment]
If you already use static templates (aka XML files) you do not need to run this wizard.

**Comment by hrdyy** [comment]
Yeah I know that but i would suggest instead of throwing an exception to catching it and told the user that he needs to select an template.

**Comment by opi99** [comment]
Yes, could I do. ;-)

**Comment by opi99** [comment]
Hmmm, if I do not select anything, I get the count error some lines above: StaticDataUpdateController.php line 153

```
        if (count($writeIds)) {
            $writeDsIds = array_keys($writeIds);
        }
```

**Comment by darthnorman** [comment]
`PHP Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/htdocs/typo3conf/ext/templavoilaplus/Classes/Controller/Update/StaticDataUpdateController.php line 153`
Get this during first step of migration in the static DS Wizard (Check Paths). PHP 7.2, T3 8.7.24

**Comment by darthnorman** [comment]
Workaround: I removed the count() function so it is only tested if $writeIds exists. The wizard does its thing now.

**Comment by opi99** [comment]
@darthnorman Do you have templates which need to be migrated to static?

**Comment by darthnorman** [comment]
4 page and 12 fce data structures were migrated.
Do you consider these "templates"? From my understanding only data structures get migrated to static files?

**Comment by opi99** [comment]
Yes, I meant data structures and not templates.
So you had 4 page and 12 fce DS (data structures) in your DB and migrated them to static ones (aka XML files)? And you got that error, but you also selected DS to migrate in step 1?

**Comment by darthnorman** [comment]
Yes, those were migrated. I got the error during migration in step 1: "checking paths" where the migration paths (aka place where the XML files are stored) get checked wether they are valid and writeable. I didn't select anything at this point. After I removed the "count()" function from line 153 I could select the templates I wanted to migrate.

**Comment by opi99** [comment]
Ok ... need to rethink this part ... need to checkout another old installation. :D
