### ISSUE TITLE
Non-admins cannot insert Content

### ISSUE THREAD

**Issue by Schweriner** [pluspol-interactive/templavoilaplus#233]
I've got a problem in a 8 LTS system using Templavoilaplus. User which are not admins are not able to insert Content to the Templavoilaplus page columns. In the log I saw: Attempt to modify record (pages) without permissions. Indeed those users are not allowed to edit pages.
I guess the problem is that inserting contents requires the templavoilaplus database fields to be updated which is not allowed - however this worked in 7 LTS without permissions.
Is there a way to enable Contentelement inserting without giving the users permissions to edit pages?

**Comment by jpmschuler** [comment]
The relation is saved in `pages.tx_templavoilaplus_flex`. Thus, users need to edit that table. However you could fake that with overrriding the pages TCA and set all fields to `exclude`(see https://docs.typo3.org/typo3cms/TCAReference/Columns/Index.html#exclude). Afterwards allow the flex field for your poor editors and all other fields for your rich editors. If you check https://github.com/TYPO3-CMS/core/blob/master/Configuration/TCA/pages.php you see that almost every field is already exclude-able.

Nevertheless it might me more reasonable to just allow editing of pages with the default TCA values and hide the fields from the backend forms via TSconfig, but that depends on your use case.

**Comment by Schweriner** [comment]
Thanks for your advice. The problem is, that the users themself are allowed to edit those pages fields by their usergroup. The problem occurs because of the Access rights given by the "Access" module - the users are there not allowed to edit pages. Giving persmission "19" to "everybody" solves the problem...

**Comment by opi99** [comment]
So, I can close this issue?

**Comment by Schweriner** [comment]
Yes it can. But maybe this use case should be documented somewhere?

**Comment by opi99** [comment]
Maybe I misunderstand ... you have editors which do not have rights to edit pages but rights to edit content? And in 7LTS it worked but in 8LTS not?

**Comment by Schweriner** [comment]
Yes correct as you said.

**Comment by opi99** [comment]
Ok, will test this, all my editors have rights on pages ;)

**Comment by agendartobias** [comment]
This is very strange, my editor user group have premission to edit content & pages but still i get the same behaviour. Content elements are not automatically inserted in page.

Before TYPO3 9.5.8 i got the same error, but after update to 9.5.8 i got no error. Is this somehow related to https://forge.typo3.org/issues/87985 ?

Can anyone help? This is urget for us... :(

**Comment by agendartobias** [comment]
i have still problems with adding content elements automaticly on pages for non admins. But my user group have edit rights on pages :(

**Comment by opi99** [comment]
Hi, is this still an issue for you?

**Comment by opi99** [comment]
No response, so closing this issue.
