### ISSUE TITLE
Compatibility of extensions fal_Gallery / templavoilaplus

### ISSUE THREAD

**Issue by SwissFall** [pluspol-interactive/templavoilaplus#244]
Somehow the extenstions fal_gallery and templavoilaplus seam to be conflicting. In case of templavoilaplus activated I get the error message when selecting a page in the backend with the FALGALLERY plugin:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 2 passed to CoStack\FalGallery\Hooks\PluginInformation::build() must be an instance of TYPO3\CMS\Backend\View\PageLayoutView, instance of Ppi\TemplaVoilaPlus\Controller\Preview\ListController given | TypeError thrown in file [...]/typo3conf/ext/fal_gallery/Classes/Hooks/PluginInformation.php in line 62. Requested URL: https://.dev/typo3/index.php M=web_txtemplavoilaplusLayout&moduleToken=--AnonymizedToken--&id=8&

If Templavoilaplus is deactive there's no problem in the backend ... Any thoughts?

**Comment by opi99** [comment]
Will check, we may need to contact the author of fal_gallery, as he may need to change his source.

**Comment by opi99** [comment]
Hmmm, I see the issue, need to add a extension, which can connect both ;)

**Comment by opi99** [comment]
https://github.com/co-stack/fal_gallery/pull/13
So closing it here.
