### ISSUE TITLE
Adding content element on alternative language problem

### ISSUE THREAD

**Issue by agendartobias** [pluspol-interactive/templavoilaplus#246]
TYPO3 9.5.5
templavoilaplus 7.3.1 or 7.3.0 
PHP 7.2

Hey, when i want to add a content element (header,text,plugin - it doesn't matter) on translated page (alternative language id=1) the content element is not addad in page section "tx_templavoilaplus_flex". I must add it manualy -> Edit alternative lang page -> General -> scroll down to Content:[tx_templavoilaplus_flex] -> Content, and there i must find and select that record.

**Comment by mz-aimcom** [comment]
I can confirm this issue for TYPO3 9.5.5 and TV+ 7.3.0.1.

**Comment by opi99** [comment]
Question to this issue, how do you manage your languages?
With SideConfiguration or the old way with sys_languages?

**Comment by mz-aimcom** [comment]
> Hey, i am using SitesConfiguration

Me too. I'm also using Site Configuration.

**Comment by opi99** [comment]
So this issue depends on #223 and #266

**Comment by opi99** [comment]
I digged again into this issue and found out that the issue is a simple stupid one and haven't todo with my first thoughts on that. I pushed a fix for this into the 7.3.x branch, please test, so I could do another 7.3 release on monday.

**Comment by agendartobias** [comment]
It works! TNX

**Comment by opi99** [comment]
Thanks for feedback
