### ISSUE TITLE
Flexible CE's with multiple languages and end dates

### ISSUE THREAD

**Issue by discotizer** [pluspol-interactive/templavoilaplus#249]
Following strange behaviour occurs which for me seems like a non-intended one:

We're using flexible CE's and sometimes they can be nested, i.e. for sliders (first CE contains the slider mark-up code, and second CE contains an individual type of content).
When using multiple languages on the site the parent CE has to be set to multi-language in order to display everything right for every language.
In once case we had set the parent CE to default language and the nested CE to multi-language. The parent element had an end date set. Now for the default lang the element disappeared after the end date. But for the other languages it was still shown.
When we changed the lang on the parent element to multi the element disappeared on the other language pages.

**Comment by opi99** [comment]
Hi, please tell me, which version of TYPO3 and TemplaVoilà! Plus do you use.
Also you may ask in the slack channel https://typo3.slack.com/messages/templavoilaplus

**Comment by discotizer** [comment]
> Hi, please tell me, which version of TYPO3 and TemplaVoilà! Plus do you use.

typo3 v7.6.35 and TVP 7.3.1 - i haven't noticed this behaviour with prior versions.

**Comment by opi99** [comment]
`Although we have German als language ID 0 ` => Ok, something I also have.
`sometimes English is selected as standard language` => What do you mean with selected here?

**Comment by jpmschuler** [comment]
My 2 cents, although perhaps not helpful: 
We had a similar problem years ago with EXT:templavoila until we fixed the language definition in the FCE containers (e.g. sliders) to
 ```xml
<meta type="array">
        <langChildren type="integer">1</langChildren>
        <langDisable type="integer">1</langDisable>
 </meta>
``` 
however as these are only stupid containers they are not intended to be translated, only the tt_content inside is intended for translation.

**Comment by discotizer** [comment]
> My 2 cents, although perhaps not helpful:
> We had a similar problem years ago with EXT:templavoila until we fixed the language definition in the FCE containers (e.g. sliders) to

Thanks, i looked it up. Was already there :)

**Comment by discotizer** [comment]
> 
> 
> `Although we have German als language ID 0 ` => Ok, something I also have.
> `sometimes English is selected as standard language` => What do you mean with selected here?

When you enter a page with the "page tool" in "english" is pre-selected in the *translations options* instead of the "default" language.

**Comment by opi99** [comment]
Hi, do we still have any issues here?

**Comment by discotizer** [comment]
I can't tell you, as we've takes measures that all parent container should be mutil-lang. So i hasn't occured again and isn't a problem any more... but i also haven't tested it again.

**Comment by opi99** [comment]
Ok, thanks for feedback. So I close this issue as I'm on TV+ 8 development.
If the issue occurs again and needs fixed in the 7.x era please open a new issue report.
