### ISSUE TITLE
Fatal error if mod.web_txtemplavoilaplusLayout.tabList is set

### ISSUE THREAD

**Issue by echavaillaz** [pluspol-interactive/templavoilaplus#257]
Hi,

If  "mod.web_txtemplavoilaplusLayout.tabList" is set, there is a fatal error throw by "GeneralUtility" from the core with the method "trimExplode". The problem is that the value become an array and not a string.

You have to change the lines 473 to 475 in "Classes/Controller/BackendLayoutController.php" with:

```
$this->modTSconfig = array_replace_recursive(
    $this->modTSconfig,
    BackendUtility::getModTSconfig($this->id, 'mod.' . $this->moduleName)
);
```

And the problem is fixed.

Eric

**Comment by echavaillaz** [comment]
Now there is another problem with this settings, with this initialization https://github.com/pluspol-interactive/templavoilaplus/blob/master/Classes/Controller/BackendLayoutController.php#L469, the value of tabList is converted as an array in $this->pObj->modTSconfig.

Please, remove this line.

**Comment by opi99** [comment]
> PHP Warning: explode() expects parameter 2 to be string, array given in /home/opi/projects/typo3/typo3_src-git/typo3/sysext/core/Classes/Utility/GeneralUtility.php line 1302
