### ISSUE TITLE
Missing markup at mapping

### ISSUE THREAD

**Issue by olagwin** [pluspol-interactive/templavoilaplus#258]
Found in TYPO3 v8

When I want to map my template the mapping-window sometimes-often don't show complete possible markup.
Sometimes there is nothing, sometimes only parts.

When I switch between "Mode: HTML Source" and "Mode: Exploded Visual" it works with 1-2 trys that I see the node I want to map on.

Looks that this part is loaded when its needed and maybe it's not completely loaded due to speed issues. For questions just visit me on my working place.

It isn't a show-stopper, only a usability-issue I would say.

**Comment by jpmschuler** [comment]
Never experienced this here in 8LTS - perhaps the source is invalid?

**Comment by opi99** [comment]
Oh, the long time, I missed this bug report you wanted to show me.
But the code path in question is very strange, so likely I won't like to fix it for the TV+ 7.x era.

As this part gets rewritten for 8.x (and we may start without an visual editor in 8.0.0) I close this issue.
