### ISSUE TITLE
TYPO3 9.5  Wrong checkRecordUpdateAccess

### ISSUE THREAD

**Issue by hrdyy** [pluspol-interactive/templavoilaplus#261]
https://github.com/pluspol-interactive/templavoilaplus/blob/efa66ec32d8998b460ec6afba8cc8ccc4f042f9f/Classes/Service/DataHandling/DataHandler.php#L651

I got a StaticDS thats look like this
``` 
<T3DataStructure>
     <ROOT type="array">
       <el type="array">
         <field_skipnavi type="array"> </field_skipnavi>
      </el>
     </ROOT>
 </T3DataStructure>
```

The returned array from getFlexFormDS is not $dataStructArray['ROOT']['el'] its $dataStructArray['sheets']['sDEF']['ROOT']['el']

this issue cause an Error that non Admin user could not place a ContentElement on Page level

table:pages:tx_templavoilaplus_flex
```
 <?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<T3FlexForms>
    <data>
        <sheet index="sDEF">
            <language index="lDEF">
                <field index="field_content">
                    <value index="vDEF">12391,12390,12389,12388,12380,12379,7323,8864,12143,12144,12145,576,718,708</value>
                </field>
            </language>
        </sheet>
    </data>
</T3FlexForms> 
```

To Fix this Issue just add the missing Arrayparts
```               
 foreach ($data[$field]['data'] as $sheetData) {
                    if (!is_array($sheetData) || !is_array($dataStructArray['sheets']['sDEF']['ROOT']['el'])) {
                        $res = false;
                        break;
                    }
                    foreach ($sheetData as $lData) {
                        if (!is_array($lData)) {
                            $res = false;
                            break;
                        }
                        foreach ($lData as $fieldName => $fieldData) {
                            if (!isset($dataStructArray['sheets']['sDEF']['ROOT']['el'][$fieldName])) {
                                $res = false;
                                break;
                            }

                            $fieldConf = $dataStructArray['sheets']['sDEF']['ROOT']['el'][$fieldName];
                            if ($fieldConf['tx_templavoilaplus']['eType'] != 'ce') {
                                $res = false;
                                break;
                            }
                        }
                    }
                }
            }
```

**Comment by stigfaerch** [comment]
@opi99 
We have another issue happening around checkRecordUpdateAccess. I does not seem to be exactly the same. I will open an issue on the problem.
If we cannot come up with a fix ourselves, is it possible to hire you to fix it in the very near future?

**Comment by stigfaerch** [comment]
I think this might a bit more complex. Also the real question is - what is the intention with the implementation of this method?
In the method comments, it says:
` * @return mixed - "1" if we grant access and "false" if we can't decide whether to give access or not
`
I think that the reason it has become a problem, is that the way \TYPO3\CMS\Core\DataHandling\DataHandler::checkRecordUpdateAccess works has been changed.
Before if the hook call return false, then this value was not read as 'deny access':
```
if ($res === 1 || $res === 0) {
    return $res;
} else {
    $res = 0;
}
```
After this, a check was made if the record existed, and then access was granted.

In TYPO3 CMS 9, the check on the result has been changed to:
```
if (isset($res)) {
    return (bool)$res;
}
```
This means that the false value is seen as 'access denied instead'.

So one way to solve this, would be just to replace $res = false with $res = null.
But the thing is, that I really don't know if this hook method call works as intended, in the first place.
If it should work when only tx_templavoilaplus_flex is updated (and no other fields), it's probably working correctly. But if it should also work when other fields are updated, then tx_templavoilaplus_flex is not checked, as the first field (like doktype), will result in returning null.

**Comment by opi99** [comment]
Does your patch still work with TYPO3 7/8?

**Comment by stigfaerch** [comment]
@opi99 
I do not have any TYPO3 7 or 8 installations running with templavoilaplus.
But looking into \TYPO3\CMS\Core\DataHandling\DataHandler::checkRecordUpdateAccess of each version, to me it seems like it would work as expected.

TYPO3 CMS 9LTS
```
        $res = null;
        if (is_array($hookObjectsArr)) {
            foreach ($hookObjectsArr as $hookObj) {
                if (method_exists($hookObj, 'checkRecordUpdateAccess')) {
                    $res = $hookObj->checkRecordUpdateAccess($table, $id, $data, $res, $this);
                }
            }
            if (isset($res)) {
                return (bool)$res;
            }
        }
        $res = false;
```

TYPO3 CMS 8LTS
```
        $res = null;
        if (is_array($hookObjectsArr)) {
            foreach ($hookObjectsArr as $hookObj) {
                if (method_exists($hookObj, 'checkRecordUpdateAccess')) {
                    $res = $hookObj->checkRecordUpdateAccess($table, $id, $data, $res, $this);
                }
            }
        }
        if ($res === 1 || $res === 0) {
            return $res;
        }
        $res = 0;
```

TYPO3 CMS 7LTS
```
        $res = null;
        if (is_array($hookObjectsArr)) {
            foreach ($hookObjectsArr as $hookObj) {
                if (method_exists($hookObj, 'checkRecordUpdateAccess')) {
                    $res = $hookObj->checkRecordUpdateAccess($table, $id, $data, $res, $this);
                }
            }
        }
        if ($res === 1 || $res === 0) {
            return $res;
        } else {
            $res = 0;
        }
```

**Comment by opi99** [comment]
Ok, I see, wow is this source part stupid and a breaking change :-(

But on your patch you also change the dataStructArray['ROOT']['el'] ... but I don't think, that's needed and that this is correct.

**Comment by stigfaerch** [comment]
@opi99 
You are probably right. I just tried to revert that part, and things still seems to work.
I made a commit from github.com unfortunately with the wrong commit message. But I guess it's not a big deal if it's squashed.

**Comment by stigfaerch** [comment]
@opi99 Thanks :-)
