### ISSUE TITLE
TYPO3 8: Remove non used elements crashs 

### ISSUE THREAD

**Issue by opi99** [pluspol-interactive/templavoilaplus#263]
> Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 4 passed to Ppi\TemplaVoilaPlus\Configuration\FlexForm\FlexFormTools8::getDataStructureIdentifier()
> must be of the type array, null given, called in /.../typo3conf/ext/templavoilaplus/Classes/Service/ApiService.php on line 1389

**Comment by zoranilic** [comment]
I can also confirm this bug on TYPO3 v8.7.x. I have it on v7.3.1 and also before on v7.2.5.
This bug doesn't allow to delete content element in any way, from List module or from TCEForm.

**Comment by jpmschuler** [comment]
FWIW: I'm on 8.7.27 and 7.3.1 and can't reproduce this error.

Possible factors which are somewhat special here: using StaticDS only, disabled MySQL strict mode

**Comment by opi99** [comment]
The bug is real, got it on my own system, so already verified. ;-)

**Comment by foliengriller** [comment]
Got the same Error, TYPO3 8.7.27 and Templavoilaplus 7.3.1
Is there some workaround avilable?

**Comment by SilkeDX** [comment]
I get the same error when deleting a translation of an element. TYPO3 8.7.27 and Templavoilaplus 7.3.1. I tried to delete it via TV Module and via List Module.

**Comment by XeniaW** [comment]
Same problem here. Typo3 8.7.30 and TV 7.3.1

**Comment by XeniaW** [comment]
a temporary solution might be to paste the copy of the error id into the site tree, then you are able to delete the elements. Sometimes it doesn't work if you activate the page.

**Comment by opi99** [comment]
So, this happens, if the element to delete is a container and the configuration contains a pointer to a element which doesn't exists anymore.

**Comment by opi99** [comment]
As I like to do a 7.3.2 release in the next time, I like to get feedback, if the state inside the 7.3.x branch is working for you.

**Comment by XeniaW** [comment]
I've changed the version compare statement in 
typo3conf\ext\templavoilaplus\Classes\Service\ApiService.php
\typo3conf\ext\templavoilaplus\Classes\Utility\TemplaVoilaUtility.php
`if (version_compare(TYPO3_version, '8.5.0', '>='))`
and 've set it higher as a typo3 version I have. It seems to have fixed the problem but I am not quite  sure if it is truly have something to do with getFlexFormDS variable

**Comment by opi99** [comment]
I meant I've fixed the issue in the 7.3.x branch, manipulating the version_compare only leads to other pitfalls or non clean working, as then the wrong code pathes will be used.

**Comment by XeniaW** [comment]
It's working! 
Thank you very much ! :)
