### ISSUE TITLE
Issue with checkRecordUpdateAccess

### ISSUE THREAD

**Issue by urlund** [pluspol-interactive/templavoilaplus#264]
Hi,

I've updated a site to TV `7.3.1` (installed from TER) and TYPO3 `9.5.11`.

The site has a backend user group called "Editor" and a user who belongs to this group.

When I select fields for "Page" in "Allowed excludefields" making an editor able to change eg. "doktype", this fields does not show up in the array of "getExcludeListArray" here:

https://github.com/pluspol-interactive/templavoilaplus/blob/f0c9cc1f4ee55d5cfd0ac575f51e1ee67e85efa3/Classes/Service/DataHandling/DataHandler.php#L631

Because of that, this condition gets triggered (every field I select in "Allowed excludefields" triggers this line):

https://github.com/pluspol-interactive/templavoilaplus/blob/f0c9cc1f4ee55d5cfd0ac575f51e1ee67e85efa3/Classes/Service/DataHandling/DataHandler.php#L635

Since "doktype" is not an array, `$res` become `false` making my "Editor" unable to edit "doktype",  "title" etc.

I can see that the github source contains `null` instead of `false`, has some other behaviour changed regarding this issue?

**Comment by opi99** [comment]
It seams this is issue #261 you are describing. Can you check with latest code from the 7.3.x branch?

**Comment by opi99** [comment]
No response so closing this issue.
