### ISSUE TITLE
Render FCE Header doesn't work in TYPO3 9.5

### ISSUE THREAD

**Issue by Liquado** [pluspol-interactive/templavoilaplus#267]
Enabling of basic.enable.renderFCEHeader doesn't work in my TYPO3 v 9.5.11. No difference in frontend. My mistake? Many thanks for request.

**Comment by opi99** [comment]
Core: https://forge.typo3.org/issues/79622
Documentation: https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Documentation/Changelog/8.6/Breaking-79622-TypoScriptStandardHeaderHasBeenRemovedFromFluidStyledContent.rst

So this happens while using FluidStyledContent starting with TYPO3 v8 LTS
