### ISSUE TITLE
Create FCEs in FCEs not possible if saving DS in file system

### ISSUE THREAD

**Issue by mschmitz89** [pluspol-interactive/templavoilaplus#268]
If you're using the data structure as a file instead of saving it to the database and you create a FCE within another FCE (for example into a two-column-container-element) you get an error in the BE page module saying:

> Parse error: Data structure could not be resolved to a valid structure. 

When checking the tt_content data you see in field tx_templavoilaplus_ds there is missing the suffix "FILE:"

It looks like:
`templates/templavoila/ds/fce/fancy-fce.xml`
Instead of:
`FILE:templates/templavoila/ds/fce/fancy-fce.xml`

**Comment by opi99** [comment]
Which TYPO3 version? Which TV+ version? And if it is TYPO3 v8 LTS, did you run the migration wizards?

**Comment by mschmitz89** [comment]
Ups sorry, it's TYPO3 9.5.9. and TemplaVoila 7.3.1 and the Migration Wizard was initiated, when the TYPO3 Major-Update was done, some weeks ago.

**Comment by opi99** [comment]
Hmmm, but this upgrade wizard (Inside TYPO3 Upgrade) should fix this issue for all tx_templavoilaplus_ds and tx_templavoilaplus_next_ds fields.
Can you please rerun this wizard in the TYPO3 Install Tool and check if it helps?
If not, can you debug typo3conf/ext/templavoilaplus/Classes/Updates/Typo3Lts9Update.php ?

**Comment by mschmitz89** [comment]
Thank you very much!
I've found the problem. The suffix "FILE:" had to be set at the path to the XML file in TypoScript, so TYPO3 is handling this always correct.
