### ISSUE TITLE
Another BE error

### ISSUE THREAD

**Issue by DavidBruchmann** [pluspol-interactive/templavoilaplus#283]
Uncaught TYPO3 Exception
unserialize() expects parameter 1 to be string, null given

TypeError thrown in file
\typo3conf\ext\templavoilaplus\Classes\Service\ConfigurationService.php in line 43.

19 unserialize(NULL)

**Comment by DavidBruchmann** [comment]
can be changed like this, `$this->extConfig` has to be an array:

```
            if ($GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['templavoilaplus']) {
                $this->extConfig = $this->removeDotsFromArrayKeysRecursive(
                    unserialize($GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['templavoilaplus'])
                );
            } else {
                $this->extConfig = [];
            }
```

**Comment by opi99** [comment]
This part needs a bit fixups
