### ISSUE TITLE
TV Plus Page Module How to make it look like it was in the past

### ISSUE THREAD

**Issue by MichaelM84** [pluspol-interactive/templavoilaplus#284]
Hi!

I have a question about the BE TV Plus Page Module.
Is it possible to make it look like the old Templavoila Page Module? I found the old style very intuitive and easy to manage contents on pages. The newer Page Module layout slows down my working speed a lot.
Actually I am a Webdesigner with basic programming skills and here they unfortunately end.

Does someone know how I can visualize my TV Plus BE Page Module Layout like it was on the older Versions of Templavoila?

**Comment by Outdoorsman** [comment]
First click "Map" or "Re-Map"...

![image](https://user-images.githubusercontent.com/3075533/96473457-88311380-11e6-11eb-8a02-2f8defa7b85d.png)

Then do you have "Mode: Exploded Visual" selected from the Mapping Window dropdown? Is that what you're talking about? This still exists in Templavoilaplus.

![image](https://user-images.githubusercontent.com/3075533/96473753-de05bb80-11e6-11eb-84cc-129fb270aea6.png)

**Comment by jpmschuler** [comment]
@Outdoorsman That is the template mapping view in Templavoila+ Module, @MichaelM84 mentioned the page module.

@MichaelM84 Could you explain what you expect? I don't know of any differences from EXT:templavoila page module to EXT:templavoilaplus page module - perhaps a screenshot or something? I used EXT:templavoila since TYPO3 v4.2 and can't remember it being different.

**Comment by Outdoorsman** [comment]
I'm not sure I know of anything particularly different either. Was an easy transition.

**Comment by opi99** [comment]
Hi @ MichaelM84 
as the style of the BE Modul didn't really changed in the last 10 years (small CSS corrections) I need help from you, what do you mean especially. Do you have screenshots or something more describing your issue?

**Comment by MichaelM84** [comment]
Hi!

Exactly I meant the TV Page Module.
I try to attach images to explain the problem better.

The OLD VIEW
![Bildschirmfoto1](https://user-images.githubusercontent.com/71593376/96968208-ef193a00-1510-11eb-8ed5-a79c2fe3fb59.jpg)

THE NEW VIEW
![Bildschirmfoto2](https://user-images.githubusercontent.com/71593376/96968247-02c4a080-1511-11eb-8f93-d027280ac43c.jpg)

As you can see, in the old view, main containers were automatically aligned horizontally and  elements inside that vertically with a preview of all the contents.
In the new view i see only a list. Everything just aligned vertically.

**Comment by opi99** [comment]
![Screenshot_20201023_160051](https://user-images.githubusercontent.com/1672061/97013148-ffe5a200-1548-11eb-8f43-cc3bba3394e9.png)

You selected the "Outline mode", uncheck the checkbox inside "Advanced Features" to get to the "Normal View"

**Comment by MichaelM84** [comment]
> ![Screenshot_20201023_160051](https://user-images.githubusercontent.com/1672061/97013148-ffe5a200-1548-11eb-8f43-cc3bba3394e9.png)
> 
> You selected the "Outline mode", uncheck the checkbox inside "Advanced Features" to get to the "Normal View"

That was simple :) THANK YOU! Feel a bit like a Noob right now :)
