### ISSUE TITLE
TYPO3 v11 compatibility

### ISSUE THREAD

**Issue by opi99** [pluspol-interactive/templavoilaplus#285]

**Comment by opi99** [comment]
https://forge.typo3.org/issues/87550

**Comment by opi99** [comment]
https://forge.typo3.org/issues/88746

**Comment by opi99** [comment]
https://forge.typo3.org/issues/93029

**Comment by opi99** [comment]
https://forge.typo3.org/issues/93885

**Comment by opi99** [comment]
`class.ext_update.php handling removed`
https://forge.typo3.org/issues/93083

**Comment by Outdoorsman** [comment]
Now that we have TYPO3 11 LTS, `templavoilaplus` 8.0.0 should be able to released without as many future modifications. It seeeems like things are getting closer to version 8 release??? TYPO3 version 12 should be announced soon.

**Comment by opi99** [comment]
The Frontend and Backend are working with TYPO3 v10 and v11, so closing this master issue/feature
