### ISSUE TITLE
Remove <p> tag in RTE just for specific Templavoilaplus mapped fields

### ISSUE THREAD

**Issue by MichaelM84** [pluspol-interactive/templavoilaplus#286]
I explain my problem.

I map my whole templates with templavoilaplus.
So for example sometimes I need h1, h2, h3 etc. fields to be mapped as RTE and not as simple input fields,  to be able to give them additional styling (f.e. bold, italic etc.).

Now when I do that, typo3 puts the <p></p> tag around them ending in code like `<h1><p>some text</p></h1>` is there a way to disable this p-tag behavior just for specific fields mapped as RTE? So not for all RTE's but just for specific ones. Unfortunately I am not that Pro in Typoscript to solve this on my own.

**Comment by MichaelM84** [comment]
i forgot to wrap the html correctly:
so it results in:
`<h1><p>some text</p></h1>`

**Comment by opi99** [comment]
Only as hint, didn't tried and so don't know if it is a solution, but may help to dive into:

As configuration for this field you have normally in your DataStructure something like
```
            <field_teaser_text type="array">
                <tx_templavoilaplus type="array">
                    <eType>rte</eType>
                    <TypoScript><![CDATA[
10 = TEXT
10.current = 1
10.parseFunc = < lib.parseFunc_RTE
]]></TypoScript>
                    <proc type="array">
                        <int>0</int>
                        <HSC>0</HSC>
                        <stdWrap></stdWrap>
                    </proc>
                </tx_templavoilaplus>
                <TCEforms type="array">
                    <label>LLL:fileadmin/templates/language_definitions/fce_template_strings.xml:field_copy</label>
                    <config type="array">
                        <type>text</type>
                        <cols>48</cols>
                        <rows>5</rows>
                        <softref>typolink_tag,images,email[subst],url</softref>
                        <enableRichtext type="boolean">1</enableRichtext>
                        <richtextConfiguration>default</richtextConfiguration>
                    </config>
                </TCEforms>
            </field_teaser_text>
```

Define in TypoScript something similar lib.parseFunc_RTE but without the <p>-Tag wrap and assign this in your DataStructure to the 10.parseFunc but, maybe the <p>-Tag is already saved in Database by the rte editor configuration.

**Comment by jpmschuler** [comment]
I'd +1 that idea for debugging and even say that a small adaption would help in debugging even more. In the data structure you could use:
```xml  
<TypoScript>
    <![CDATA[
     10 < lib.templavoila.teaser_text
     ]]>
</TypoScript>
```

and in typoscript you could use:

```ini
lib.templavoila.teaser_text = TEXT
lib.templavoila.teaser_text.current = 1
lib.templavoila.teaser_text.parseFunc = < lib.parseFunc_RTE
```
That way for each test and override of the `parseFunc` and change you just change the TypoScript (in Backend, IDE, whatever suits you best), instead of the datastructure (which might would need a mapping update after a change).

**Comment by opi99** [comment]
@MichaelM84 Could you resolve your issue?

**Comment by opi99** [comment]
No response so closing this issue.
