### ISSUE TITLE
Version 8 Update Script: jQuery is not available '$ is not defined'

### ISSUE THREAD

**Issue by PeaceSfiSh** [pluspol-interactive/templavoilaplus#287]
`Your system runs TYPO3 9.5.22 and TV+ 8.0.0-alpha.6. Your TYPO3 Version is supported by TV+ 8.`

Within step 2 a small Javascript is used to enable the "Continue with step 3"-button, but jQuery is not available while the script should be triggered.

`index.php?route=%2Ftools%2FExtensionmanagerExtensionmanager%2F&token=824981f219a2a08231efa6d2db20c52af7490bee&tx_extensionmanager_tools_extensionmanagerextensionmanager[extensionKey]=templavoilaplus&tx_extensionmanager_tools_extensionmanagerextensionmanager[action]=show&tx_extensionmanager_tools_extensionmanagerextensionmanager[controller]=UpdateScript:449 Uncaught ReferenceError: $ is not defined`

**Comment by opi99** [comment]
As of https://forge.typo3.org/issues/93083 I should use an API, which have no abilities to get upgrades working as it should :-( so, at the moment, I'm forced to rewrite many parts to get it working there. Damn.
But for the moment, I think I will fix this.
