### ISSUE TITLE
Version 8 Update Script: type-safe comparsion not possible in TemplaVoilaPlus8UpdateController

### ISSUE THREAD

**Issue by PeaceSfiSh** [pluspol-interactive/templavoilaplus#288]
`Your system runs TYPO3 9.5.22 and TV+ 8.0.0-alpha.6. Your TYPO3 Version is supported by TV+ 8.`

While migrating the data structure the script wasn't able to find a matching "path". The reason was a type incompatibility in the getDsForTo-Method. 

The comparsion didn't match for 
$ds['path'] = 8; (int)
$to['datastructure'] = "8"; (string)

I solved this by using a non-type-safe comparsion, maybe a cast is possible too. 

```php
   protected function getDsForTo(array $allDs, array $to): array
    {
        foreach ($allDs as $ds) {
            if ($ds['path'] == $to['datastructure']) {
                return $ds;
            }
        }
        throw new \Exception('DataStructure "' . $to['datastructure'] . '" not found for Template Object with uid "' . $to['uid'] . '"');
    }
```

**Comment by opi99** [comment]
Hi,

the $ds['path'] value shouldn't be integer it should be a string, do you have DataStructure in Database or in static files?

**Comment by PeaceSfiSh** [comment]
DataStructure is stored in the Database

**Comment by opi99** [comment]
Hmmm, this is curious, we read all DS from database with
```
        foreach ($result as $row) {
            $dataStructure = [
                'staticDS' => false,
                'title' => $row['title'],
                'path' => $row['uid'],
                'xml' => $row['dataprot'],
                'scope' => $row['scope'],
                'icon' => $row['previewicon'],
                'belayout' => $row['belayout'], // This should be in TO or is that only there for staticDS??
            ];

            $allDs[] = $dataStructure;
        }
```

So, no conversion from string (from database) into integer. And I use this field as string (so this could also break other parts).
I don't know what happens, may newer PHP versions convert this automagically (depending on SQL field type?) ... so we should cast it here to string.

Can you apply following patch and test again?
```
        foreach ($result as $row) {
            $dataStructure = [
                'staticDS' => false,
                'title' => $row['title'],
                'path' => $row['uid'],
                'xml' => $row['dataprot'],
                'scope' => $row['scope'],
                'icon' => $row['previewicon'],
                'belayout' => $row['belayout'], // This should be in TO or is that only there for staticDS??
            ];

            $allDs[] = $dataStructure;
        }
```
