### ISSUE TITLE
Version 8 Update Script: Error if no mapping for template object is available

### ISSUE THREAD

**Issue by PeaceSfiSh** [pluspol-interactive/templavoilaplus#289]
`Your system runs TYPO3 9.5.22 and TV+ 8.0.0-alpha.6. Your TYPO3 Version is supported by TV+ 8.`

If a template object is not configured correctly (**no mapping**) a PHP error appears.

`
Argument 2 passed to Tvp\TemplaVoilaPlus\Controller\Backend\Update\TemplaVoilaPlus8UpdateController::convertDsTo2mappinglnformation() must be of the type array, null given, called in /var/www/html/public/typo3conf/ext/templavoilaplus/Classes/Controller/Backend/Update/TemplaVoilaPlus8UpdateController.php on line 988
in /var/www/html/public/typo3conf/ext/templavoilaplus/Classes/Controller/Backend/Update/TemplaVoilaPlus8UpdateController.php line 1152
`

The template object should be configured correctly before starting an update, but if not it breaks the update process.

**Comment by opi99** [comment]
Hi, could you show me your DataStructure und TemplateObject for this issue? So I could better filter this?

**Comment by PeaceSfiSh** [comment]
Hej, sorry for the late reply. I needed to pull out a database backup, because the mapping was fixed already.

That's the serialized mapping information (no mapping) causing an error:
`a:2:{s:11:\"MappingInfo\";a:0:{}s:18:\"MappingData_cached\";N;}`

That's the fixed, non-breaking version of the field:
`a:2:{s:11:\"MappingInfo\";a:1:{s:4:\"ROOT\";a:2:{s:6:\"MAP_EL\";s:13:\"body[1]/INNER\";s:2:\"el\";a:1:{s:13:\"field_content\";a:1:{s:6:\"MAP_EL\";s:6:\"div[1]\";}}}}s:18:\"MappingData_cached\";a:2:{s:6:\"cArray\";a:3:{i:0;s:339:\"\r\n  <header id=\"page-header\">\r\n    <div class=\"row\">\r\n      <div class=\"large-4 medium-12 columns\">\r\n        <div class=\"logo-wrap\">\r\n          <div class=\"logo\"></div>\r\n        </div>\r\n      </div>\r\n      <div class=\"large-8 medium-12 columns\">\r\n        <nav></nav>\r\n      </div>\r\n    </div>\r\n  </header>\r\n  <div class=\"banner\"></div>\r\n  \";s:13:\"field_content\";s:11:\"<div></div>\";i:2;s:56:\"\r\n  <footer>\r\n    <div class=\"row\"></div>\r\n  </footer>\r\n\";}s:3:\"sub\";a:1:{s:13:\"field_content\";a:2:{s:6:\"cArray\";a:1:{i:0;s:11:\"<div></div>\";}s:3:\"sub\";a:0:{}}}}}`

**Comment by opi99** [comment]
Thanks for feedback, checking this now in Step1
