### ISSUE TITLE
Reference Index cant update for Flexforms anymore

### ISSUE THREAD

**Issue by Schweriner** [pluspol-interactive/templavoilaplus#294]
The XCLASS of the FlexFormTools currently causes the TYPO3 system to be unable to update the reference index for any flexform field in the system at the moment.
This is caused by this line:
https://github.com/pluspol-interactive/templavoilaplus/blob/master/Classes/Configuration/FlexForm/FlexFormTools8.php#L213

$lKey is undefined here which causes that the upfollowing the following traverseFlexFormXMLData_recurse function doesnt receive any data for the fields. So that function is unable to process any references at all.

Change that line to ``$lang = 'lDEF';`` solves the problem for systems with one language, but we should fallback to the for-loop around each language as it is in the original FlexformTools or earlier versions of this Hook.

**Comment by opi99** [comment]
Oh, which TYPO3 version and TV+ version do you use?

**Comment by Schweriner** [comment]
TYPO3 9.5.26 and TVP 7.3.3
