### ISSUE TITLE
v10: Missing composer dependency declaration to typo3/cms-form

### ISSUE THREAD

**Issue by jpmschuler** [pluspol-interactive/templavoilaplus#296]
Installing a 8 alpha resulted in an exception here, because a class from TYP03/CMS/Forms was missing. Adding a require for `typo3/cms-form:*` to my project resolved this, thus it should be added as a composer dependency.

**Comment by opi99** [comment]
Were did it come? While trying editing in ControlCenter?
The stuff to ext:form will be removed (or moved into another extension) it costs me to much time.

**Comment by jpmschuler** [comment]
After composer install, running `vendor/bin/typo3cms language:update` threw the exception.
As this is part of our default deploy routine I never made it to frontend or backend.

**Comment by opi99** [comment]
Oh, ok, wundersam.
