### ISSUE TITLE
Problem when editing page properties.

### ISSUE THREAD

**Issue by Treedent** [pluspol-interactive/templavoilaplus#32]
When I edit some page properties, then save, all the content of my page are Unlinked from their columns. What makes your extension impracticable.
I have use the import from Old version 1.9.2 and all seems to be ok.

**Comment by opi99** [comment]
You have TYPO3 7 LTS, right?

I found an issue with the update script which should have bring a warning. Fixed that in #33 so the migration shouldn't have worked correctly. ;)
So if you edit the page property following happens:
- The field with selected TemplaVoilà Template Object shows the hint "Value not allowed"
- If you save this now, the field gets reseted to empty value (so you lost the old configured TemplaVoilà Template Object)
- As no TemplaVoilà Template Object is selected anymore, nothing is linked inside page.

How to fix it:
- We need to migrate the databases correctly.
- 2 ways,
-- check out the git repository and do the migration again (Should be no problem for you as you do not have Data Structures or Template Objects yet)
-- or wait till I release 7.0.2 to TER and do the migration then again.

Hope I could help you.

**Comment by Treedent** [comment]
Yes, I use V7.6.16.
The import process with TVplus 7.0.1 in your 2 new tables seems ok.
In the Appearence Tab, the Select box displaying Template Object is OK as well.
But when editing page properties, the General Tab does not load content in appropriate fields. No content here, for each column.

**Comment by opi99** [comment]
So you have content in "tx_templavoilaplus_tmplobj"?
Did you cleared the System-Cache?

**Comment by Treedent** [comment]
Yes several times

**Comment by opi99** [comment]
And you have content in "tx_templavoilaplus_tmplobj"?

**Comment by Treedent** [comment]
yes

**Comment by opi99** [comment]
Hmmm, however this has worked, as there was a bug in it.
Did you use this git before the 7.0 release?
On my different (live-)systems I don't get such an issue.

**Comment by Treedent** [comment]
When I edit a page row in PhpMyadmin, the field 'tx_templavoila_flex' looks like this :
`<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<T3FlexForms>
    <data>
        <sheet index="sDEF">
            <language index="lDEF">
                <field index="field_rotator">
                    <value index="vDEF">2194</value>
                </field>
                <field index="field_block1">
                    <value index="vDEF">3358</value>
                </field>
                <field index="field_block2">
                    <value index="vDEF">3359</value>
                </field>
                <field index="field_block3">
                    <value index="vDEF">3360</value>
                </field>
                <field index="field_block4">
                    <value index="vDEF">3361</value>
                </field>
                <field index="field_middle_content">
                    <value index="vDEF">3064,3065</value>
                </field>
                <field index="field_right_content">
                    <value index="vDEF"></value>
                </field>
                <field index="field_actuevents">
                    <value index="vDEF">2300</value>
                </field>
            </language>
        </sheet>
    </data>
</T3FlexForms>`

Is there any change for this in your version ?

**Comment by opi99** [comment]
And what is in your 'tx_templavoilaplus_flex' field?

**Comment by Treedent** [comment]
Exactly the same : 
`<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<T3FlexForms>
    <data>
        <sheet index="sDEF">
            <language index="lDEF">
                <field index="field_rotator">
                    <value index="vDEF">2194</value>
                </field>
                <field index="field_block1">
                    <value index="vDEF">3358</value>
                </field>
                <field index="field_block2">
                    <value index="vDEF">3359</value>
                </field>
                <field index="field_block3">
                    <value index="vDEF">3360</value>
                </field>
                <field index="field_block4">
                    <value index="vDEF">3361</value>
                </field>
                <field index="field_middle_content">
                    <value index="vDEF">3064,3065</value>
                </field>
                <field index="field_right_content">
                    <value index="vDEF"></value>
                </field>
                <field index="field_actuevents">
                    <value index="vDEF">2300</value>
                </field>
            </language>
        </sheet>
    </data>
</T3FlexForms>
`

**Comment by Treedent** [comment]
That's it. 
When saving page properties, the content IDs are not retained in VDEF index.
`<value index="vDEF">5883</value>`
becomes
`<value index="vDEF"></value>`

**Comment by opi99** [comment]
So your Data above is before saving?

**Comment by Treedent** [comment]
Am I the only one who have this bug or can you reproduce it ?

**Comment by Treedent** [comment]
Section ? Where ?

**Comment by Treedent** [comment]
Can we talk about that bug trought a chat app (Skype or others). Are you busy ?

**Comment by opi99** [comment]
We can write on slack https://typo3.slack.com/messages/templavoila/ and yes it seams you are the only one with this issue.
And I've also other things to do as waiting for issue comments.

**Comment by opi99** [comment]
And still my question "Did you use this git before the 7.0 release?" isn't answered.

**Comment by Treedent** [comment]
Yes I use the git 7.0 before

**Comment by opi99** [comment]
And it worked before the naming migration?

**Comment by Treedent** [comment]
No, never

**Comment by Treedent** [comment]
Before migrating data with 7.01, I just delete/reimport  the page, page_language_overlay and tt_content table from old site with TV 1.9.2.
I also add t3ver_move_id field to old TV tables to make migration sql script work.

**Comment by opi99** [comment]
Why didn't you open up an issue report earlier?
Anyway, how much data could you send me from your system, to get your issue reproduced?

**Comment by Treedent** [comment]
I have found the problem. I have deactivated the "compatibility6" extension and the content are now present in the General tab when I edit page properties. 
I don't understand why compatibility6 extension causes problems at this point.
Sorry for the inconvenience.

**Comment by opi99** [comment]
Ok, I understand ... will close this issue and open a new one.
I understand what breaks, maybe I can stop compat6 to do this or I need to mark this as extension in conflict.

**Comment by Treedent** [comment]
I will appreciate if you can make compatibility6 compatible with TV+. LOL.

**Comment by opi99** [comment]
Do you need the compatibility6 extension? It's hard to get loaded afterwards.

**Comment by opi99** [comment]
Opened #40 as I've a solution in mind.
