### ISSUE TITLE
Non-static method Ppi\TemplaVoilaPlus\Utility\TemplaVoilaUtility::getUseableLanguages()

### ISSUE THREAD

**Issue by tobiasquadflieg** [pluspol-interactive/templavoilaplus#320]
Hey, 
u try to call a non-static method in a static context this cause an exception.

System: 
TYPO3-Version	9.5.31
Webserver	nginx/1.20.1
PHP-Version	7.2.34-22+0
Database (Default)	MySQL 5.5.5-10.3.30-MariaDB

Extension: templavoilaplus v7.3.4

https://github.com/pluspol-interactive/templavoilaplus/blob/54ab00467063923d56775c5b9f6aa6cad0d7cfb7/Classes/Utility/TemplaVoilaUtility.php#L126

solution: just make the function static

```
public static function getUseableLanguages(int $pageId = 0)
    {
...
    }
```

**Comment by opi99** [comment]
Ok, fixed in branch, I would also be fine todo an 7.3.5 release ... but maybe, I like to wait shortly, if you find some more issues.
