### ISSUE TITLE
Compatibility issue with MySQL 5.7

### ISSUE THREAD

**Issue by danielkoch** [pluspol-interactive/templavoilaplus#324]
I'm using templavoila `8.0.0-beta.1`with MySQL `5.7.34` and get the following Doctrine\DBAL\Exception\DriverException:
**2/2**
```
An exception occurred while executing 'SELECT COUNT(`uid`), `uid`, `tx_templavoilaplus_to`, `tx_templavoilaplus_next_to` FROM `pages` WHERE ((`tx_templavoilaplus_to` <> ?) OR (`tx_templavoilaplus_next_to` <> ?)) AND (`pages`.`deleted` = 0) GROUP BY `tx_templavoilaplus_to`, `tx_templavoilaplus_next_to`' with params ["", ""]: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'db_name.pages.uid' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

**1/2**
```
Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'db_name.pages.uid' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

Any chance to get it compatible with the mentioned MySQL version?

**Comment by opi99** [comment]
Hi,

can you tell me, where do you get this error? Looks like while starting the Update Script to migrate to version 8.
I used MySQL 5.7 / MariaDB 10.3 but not in strict mode and so maybe there are more issues like that ... my bad :-/

**Comment by jpmschuler** [comment]
That GROUP_BY error is a strict mode thing; you should disable `ONLY_FULL_GROUP_BY`- most other strict mode stuff makes sense, but refactoring SQL statements to avoid this is often not possible without touching surrounding code.

The background is: we have a count and grouped by to/next_to, thus uid is just one random example. That's why it is forbidden to be in the SELECT during strict mode. If you need an example uid, either get min/max or make a second query.

**Comment by danielkoch** [comment]
> Hi,
> 
> can you tell me, where do you get this error? Looks like while starting the Update Script to migrate to version 8. I used MySQL 5.7 / MariaDB 10.3 but not in strict mode and so maybe there are more issues like that ... my bad :-/

I got the error after starting the "upgrade wizard".

**Comment by danielkoch** [comment]
> That GROUP_BY error is a strict mode thing; you should disable `ONLY_FULL_GROUP_BY`- most other strict mode stuff makes sense, but refactoring SQL statements to avoid this is often not possible without touching surrounding code.
> 
> The background is: we have a count and grouped by to/next_to, thus uid is just one random example. That's why it is forbidden to be in the SELECT during strict mode. If you need an example uid, either get min/max or make a second query.

Yes, I changed my database configuration and it worked. Thank you for your answer!

**Comment by opi99** [comment]
The fix would be to add "min(uid) as uid" to the select statement ... but, sadly that isn't supported by the ORM, this will lead to the following SQL Statement
```SELECT `min(uid)` as `uid` ...```
So, will close this as unfixable only disabling the ONLY_FULL_GROUP_BY on SQL Server is the possible way.
