### ISSUE TITLE
Php warning in Update configuration to TemplaVoilà! Plus 8

### ISSUE THREAD

**Issue by novodevsas** [pluspol-interactive/templavoilaplus#325]
Hello,
I updated from typo3 9 to 10. I installed the templavoilaplus 8 well but when I want to update I have this error: "PHP Warning: fopen (*** / typo3conf / ext / test_tepmpl / Configuration / TVP / DataStructurePlaces.php): failed to open stream: No such file or directory in *** / typo3 / sysext / core / Classes / Utility / GeneralUtility.php line 1845 "
I've been on it for two days, the Configuration / TVP folder is not created in the extension I chose.
Thanks for your help

**Comment by Boeneke** [comment]
Hello, 
same here with lastest version 8.0.0-beta.1 and TYPO3 10.4.22 (still symlink version)

Update configuration to TemplaVoilà! Plus 8
Step 1 - Check your System:  O.K.
Step 2 - Select target: Selected only available option "new extension" 
Step 3 - Create new Extension: vendor and extension name used
Step 4 - Extension created/updated:

Error
PHP Warning: fopen(/var/www/vhosts/gg2.online-now.de/httpdocs/typo3conf/ext/ontvdata/Configuration/TVP/DataStructurePlaces.php): failed to open stream: No such file or directory in /.../typo3_src-10.4.22/typo3/sysext/core/Classes/Utility/GeneralUtility.php line 1848

-> extension directory is created
-> composer.json, ext_emconf.php and ext_localconf.php are created only

Thanks for any info and help concerning this issue (i know - still beta version)
michael

**Comment by jpmschuler** [comment]
I can reproduce this in a composer environment, too. 
Workaround: If you add the folders (plural, there are similar follow-up errors) manually and chmod them correctly the files will be created.

**Comment by opi99** [comment]
Ok, this is caused by https://forge.typo3.org/issues/82702 where the second parameter to mkdir_dir was deprecated in TYPO3 v9 and removed in v10
