### ISSUE TITLE
TemplaVoilaPlus8UpdateController::createPath is broken

### ISSUE THREAD

**Issue by weberdigital** [pluspol-interactive/templavoilaplus#326]
Hi,

there is a typo in the method TemplaVoilaPlus8UpdateController::createPath.

Wrong:
`            GeneralUtility::mkdir_deep($publicExtensionDirectory, $subPath);`

Right:
`            GeneralUtility::mkdir_deep($publicExtensionDirectory. $subPath);`

Thanks for fixing.

**Comment by jpmschuler** [comment]
This is the technical explanation for #325
