### ISSUE TITLE
Doctrine\DBAL\Exception\InvalidFieldNameException in update script

### ISSUE THREAD

**Issue by fhamelin** [pluspol-interactive/templavoilaplus#328]
The update script throws the following error on the first step.
```
Doctrine\DBAL\Exception\InvalidFieldNameException
An exception occurred while executing 'SELECT COUNT(`uid`), `min(uid)` AS `uid`, `tx_templavoilaplus_to`, `tx_templavoilaplus_next_to` FROM `pages` WHERE ((`tx_templavoilaplus_to` <> ?) OR (`tx_templavoilaplus_next_to` <> ?)) AND (`pages`.`deleted` = 0) GROUP BY `tx_templavoilaplus_to`, `tx_templavoilaplus_next_to`' with params ["", ""]: Unknown column 'min(uid)' in 'field list'
```

I looked into it and it seems the `addSelect()` function in the query builder does not work with the SQL MIN function.

Replacing this line in class `Tvp\TemplaVoilaPlus\Controller\Backend\ControlCenter\TemplaVoilaPlus8UpdateController`
```
->addSelect('min(uid) as uid', 'tx_templavoilaplus_to', 'tx_templavoilaplus_next_to')
```
by this should fix it.
```
->addSelectLiteral('min(uid) as uid')  
->addSelect('tx_templavoilaplus_to', 'tx_templavoilaplus_next_to')
```
If you want, I can submit a PR for this.

**Comment by jpmschuler** [comment]
I tried to work around it by separating the min from the select part tonight as I thought this would be necessary, but that felt awkward and your solution is quite elegant.
It would be wonderful if you create a PR, I could`composer-patches` it to check it on my installs so we can get it in the code base easily. (Have still 6 templates to convert)

**Comment by opi99** [comment]
Oh, I commited code, that I only tried for testing. But, wow, I didn't know this solution, so the accident commit helps me to find a good solution.
Thank you.
