### ISSUE TITLE
PHP-Error: Call to undefined method PageRepository::getFirstWebPage()

### ISSUE THREAD

**Issue by jpmschuler** [pluspol-interactive/templavoilaplus#332]
TYPO3 10LTS, TVP 8:e33d87f
In the Backend go to Page Module, select a page which is of type shortcut with subtype "first child page"
templavoilaplus/Classes/Controller/Backend/Handler/DoktypeShortcutHandler.php line 54
creates a (1/1) Error
Call to undefined method TYPO3\CMS\Core\Domain\Repository\PageRepository::getFirstWebPage()

Probably a simple deprecation, will create PR if time comes up.

Shortcut with subtype "selected page" works fine

**Comment by opi99** [comment]
Function was deprecated in v9 https://forge.typo3.org/issues/85971
