### ISSUE TITLE
After migration of BE elements from templavoila to templavoilaplus can't delete any content in BE.

### ISSUE THREAD

**Issue by dinura** [pluspol-interactive/templavoilaplus#52]
Please change following code in Classes\Service\ApiService.php 
$valueItems = GeneralUtility::intExplode(',', $value);  to $valueItems = GeneralUtility::intExplode(',', (string)$value); on lines 1051 and 1104.

**Comment by opi99** [comment]
You are getting an array as value here, it's not save to declare this as string.
So the question would be ... why it is an array and not a string with comma separated uids?

As the source didn't changed in the last 3 years, and I don't get it on my instances, I've following questions:
* From which TemplaVoila/TYPO3 version did you upgraded to which TYPO3/TemplaVoilà Plus version?
* How did you run the Update and Migration?
* Where do you try to delete? (TV page module or list module? Or with the clipboard?)

**Comment by opi99** [comment]
Close as no response is given.
