### ISSUE TITLE
staticDsFolder can't be of type EXT:myext/<something> or /typo3conf/ext/myext/<something>

### ISSUE THREAD

**Issue by jpmschuler** [pluspol-interactive/templavoilaplus#63]
Working on https://github.com/jpmschuler/templavoilaplus/issues/4 (allowing multiple staticDsFolders) I found that one can only set staticDsFolders to anything inside a filestorage (e.g. fileadmin/), probably due to FAL usage for file lookup.

As it is best practice to define a template as an extension, allowing paths like EXT:myext/<something> or /typo3conf/ext/myext/<something> might be good idea.

**Comment by opi99** [comment]
Do you mean the "static ds.staticDS.path_fce" and "static ds.staticDS.path_page" extension configuration option?
IMHO paths like /typo3conf/ext/myext/ should work. Using multiple paths is something on my own TODO list, but needs conceptional thinking.

**Comment by jpmschuler** [comment]
Sorry, seems to be have been a local problem with file access permissions
```
typo3conf/ext/myext/mysubfolder
```
works. Thanks for the hint.

**Comment by opi99** [comment]
Thanks for response. :-)
