### ISSUE TITLE
PHP exceptions when activating either templavoilaplus or templavoila

### ISSUE THREAD

**Issue by Outdoorsman** [pluspol-interactive/templavoilaplus#64]
When I enable either one of the TV extensions I get exceptions that break the the FE and BE so nothing works at all. Not sure what to do as I can't make sense out of these exceptions.

When I activate **templavoila** I get this:
```
#1320585902: $hookObject "Ppi\TemplaVoilaPlus\Hooks\TableConfigurationPostProcessingHook" must implement interface TYPO3\CMS\Core\Database\TableConfigurationPostProcessingHookInterface (More information)

UnexpectedValueException thrown in file
/home/domainname/public_html/typo3_src-7.6.18/typo3/sysext/core/Classes/Core/Bootstrap.php in line 1024.
```
When I active **templavoilaplus** I get this:
```
#1338996122: Package "templavoila" is already registered. (More information)

TYPO3\CMS\Core\Package\Exception\InvalidPackageStateException thrown in file
/home/domainname/public_html/typo3_src-7.6.18/typo3/sysext/core/Classes/Package/PackageManager.php in line 492.
```
To get my website working after these exceptions I have to:

1. Delete the lines and block of code about templavoilaplus and templavoila from `typo3conf/LocalConfiguration.php` and from `typo3conf/PackageStates.php` *(making sure I have a backup of what I deleted in case I need it again)*
2. Do an `rm -rf typo3temp/* && touch typo3conf/ENABLE_INSTALL_TOOL`
3. Navigate to the install tool and recreate the typo3temp folders. *(sometimes I have to repeat step 2 several times before step 3 will work)*
4. Return to the backend again that now shows both extensions a uninstalled but am at least able to use TYPO3

**After doing the above steps, I click on Extensions from the BE menu and get the following exception.** But when I click the Extensions menu button again, it goes away and it's showing that both of the problem extensions are uninstalled.
```
#1: PHP Catchable Fatal Error: Argument 1 passed to TYPO3\CMS\Extensionmanager\Utility\ListUtility::getInstallTypeForPackage() must implement interface TYPO3\CMS\Core\Package\PackageInterface, null given, called in /home/domainname/public_html/typo3_src-7.6.18/typo3/sysext/extensionmanager/Classes/Utility/ListUtility.php on line 114 and defined in /home/domainname/public_html/typo3_src-7.6.18/typo3/sysext/extensionmanager/Classes/Utility/ListUtility.php line 161 (More information)

TYPO3\CMS\Core\Error\Exception thrown in file
/home/domainname/public_html/typo3_src-7.6.18/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 111.
```
I am using:

- TYPO3 7.6.18
- templavoila 2.0.0 (but also tried 2.0.4)
- templavoilaplus 7.0.5 (but also tried 7.0.4)
- PHP 5.5 (but also tried 5.6)
- Using the traditional non-composer method for this website.

My setup TS is (which was suggested [here](https://docs.typo3.org/typo3cms/extensions/templavoilaplus/FaqFrequentlyAskedQuestions/Index.html)):
```
page = PAGE
page.typeNum = 0
page.10 = USER
page.10.userFunc = Ppi\TemplaVoilaPlus\Controller\FrontendController->main_page
```
But I have also tried this setup TS (which was suggested [here](https://docs.typo3.org/typo3cms/extensions/templavoilaplus/Migration/Index.html)):
```
page = PAGE
page.typeNum = 0
page.10 = USER
page.10 < plugin.tx_templavoilaplus_pi1
page.10.userFunc = tx_templavoilaplus_pi1->main_page
```

**Comment by kuhschnappel** [comment]
same Problem, tried with Typo3 7.6.17 also

**Comment by kuhschnappel** [comment]
same Problem with 7.1.0-dev

**Comment by jpmschuler** [comment]
HOTFIX:
This problem is IMHO only the case if EXT:templavoila in existing (even not installed). A simple way to circumvent ist to remove EXT:templavoila before installing EXT:templavoilaplus.

(Of course this is still an issue)

**Comment by opi99** [comment]
I can only try to fix the templavoilaplus issue, need to find out, why the EM tries to test for an alias called "templavoila"

**Comment by kuhschnappel** [comment]
in my case i located the problem, when i activated the tvp the extmanager throw an error because of another class (PHP Fatal error:  Cannot redeclare class user_AbfalllexikonLabelClass in ...) so the installation of tvp breaks
