### ISSUE TITLE
Update documentation about TS

### ISSUE THREAD

**Issue by Outdoorsman** [pluspol-interactive/templavoilaplus#67]
I noticed you've updated the [Migration page](https://docs.typo3.org/typo3cms/extensions/templavoilaplus/Migration/Index.html) TS in the docs, but it also need to happen on the [FAQ page](https://docs.typo3.org/typo3cms/extensions/templavoilaplus/FaqFrequentlyAskedQuestions/Index.html) as far as I know?

Here's what it is now:
```
page = PAGE
page.typeNum = 0
page.10 = USER
page.10.userFunc = Ppi\TemplaVoilaPlus\Controller\FrontendController->main_page
```
Here's what I think it should be:
```
page = PAGE
page.typeNum = 0
page.10 = USER
page.10.userFunc = ExtensionTemplavoilaControllerFrontendController->main_page
```

**Comment by opi99** [comment]
The content of the Migration page is rendered false, as I did a mistake in formatting of the .rst file.
After uploading the next TER package (which will be TV+ 7.1.0), thsi should get fixed up again.

The FAQ page is correct the Migration page looks wrong (but should be fixed already).

**Comment by Outdoorsman** [comment]
Thanks for the clarification. You are one fast responder!
