### ISSUE TITLE
ClickMenu.js - File does not exist

### ISSUE THREAD

**Issue by agendartobias** [pluspol-interactive/templavoilaplus#70]
Hello, in Typo3 BE, when i click modul Page (Templavolia) i get in apache error log this line.

AH00128: File does not exist
/typo3/sysext/backend/Resources/Public/JavaScript/ClickMenu.js, referer: http://zora.elasticbox.eu/typo3/index.php?M=web_txtemplavoilaplusLayout&moduleToken=5443a02c32b33cb72ac958cbbebb0e991531043d&id=201

Can anyone help me?

**Comment by opi99** [comment]
Hmmm, are you using TYPO3 v8?

**Comment by agendartobias** [comment]
Yes Typo3 8.7.1

**Comment by opi99** [comment]
Ok, didn't recognized this yet, will look where this is gone from v7 to v8.
But this shouldn't make a problem, only clicking on the "paper" icons should fail.

**Comment by opi99** [comment]
Broken with https://review.typo3.org/#/c/50124/ for TYPO3 8.6
