### ISSUE TITLE
This is a reference to an element on page 0.

### ISSUE THREAD

**Issue by agendartobias** [pluspol-interactive/templavoilaplus#71]
Hello after a while my templavoliaplus dont work anymore. If i go to any page with "Page" module it says This is a reference to an element on page 0 and my whole content is in "Non-used elements".

I got FE error: "TemplaVoila Plus ERROR: Couldn't find a Data Structure set for table/row "pages:1". Please select a Data Structure and Template Object first."

BE error: Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1478105826: Data structure file /srv/www/typo3/mydomain/26 could not be resolved to an existing file | RuntimeException thrown in file /srv/www/typo3/typo3_source/typo3_src-8.7.1/typo3/sysext/core/Classes/Configuration/FlexForm/FlexFormTools.php in line 681. Requested URL: http://mydomain/typo3/index.php?route=%2Frecord%2Fedit&token=67b038b05ea5cff3a20fe32e0439d8bc10f5b52e&edit%5Bpages%5D%5B186%5D=edit&returnUrl=%2Ftypo3%2Findex.php%3FM%3Dweb_txtemplavoilaplusLayout%26moduleToken%3Df1d7afeff4ba52c832f6530618595401df2f2385%26id%3D186

Can anyone help me please?

**Comment by opi99** [comment]
Hi,

it seams you changed the selection of the template on the page id = 1 to nothing.
Hmmm, damn that the FlexFormTools from v8 are failing on empty selection.

**Comment by agendartobias** [comment]
Maybe those two picture help you

WRONG database record: https://filebox.agenda.si/index.php/s/ii3n8S3Yebehtp8 (as you see tx_templavoilaplus_ds is defined "FILE:11" if i fix that to only "11" everything works again. This wrong database record happens at random times

FIXED database record: https://filebox.agenda.si/index.php/s/Xue1VXC9wsWWS2X

**Comment by opi99** [comment]
*hmpf* I hate some changes in v8, ok thx for this information ... will be hard to fix, but will try my best. ;)

**Comment by opi99** [comment]
One core issue in this same field: https://forge.typo3.org/issues/79101

**Comment by opi99** [comment]
Resolving #73 should already help a little bit.

**Comment by opi99** [comment]
Ok, will push a change which fixes the wrong message and create a new issue about the record change.
