### ISSUE TITLE
Missing "Clean up XML" functionality (cm2-Module)

### ISSUE THREAD

**Issue by fgerards** [pluspol-interactive/templavoilaplus#72]
If one activates the "show outline" advanced function in the page module and clicks on the link "Click to clean up XML..." (shows up if any incorrect flexform-structures were saved on the page), an error occurs.

Also, the "Clean XML of all dirty elements above!" button has no functionality.

This all resembles to the "cm2" Module in old TemplaVoila, which is now missing.

**Comment by opi99** [comment]
It is not missing ... but the URLs changed, as links to "index.php" are not allowed anymore. ;-)

**Comment by agendartobias** [comment]
Maybe those two picture help you

WRONG database record: https://filebox.agenda.si/index.php/s/ii3n8S3Yebehtp8 (as you see tx_templavoilaplus_ds is defined "FILE:11" if i fix that to only "11" everything works again. This wrong database record happens at random times

FIXED database record: https://filebox.agenda.si/index.php/s/Xue1VXC9wsWWS2X

**Comment by opi99** [comment]
Fixed without testing, as I do not have the situation yet somewhere, so please test from git.
