### ISSUE TITLE
v8: Sections of a FCE not shown in the Backend in TYPO3 8.7.1

### ISSUE THREAD

**Issue by sytura** [pluspol-interactive/templavoilaplus#76]
Hi,

I tried migrating from TYPO3 6.2 and TV 1.9.2. The migration to TYPO3 7.6 works well in front and backend. 

But templavoilaplus does not work well in TYPO3 8.7. The frontend is ok. But I can't edit sections in the Backend. In the following screenshot you can see the problem with a simple slider:

Screenshot:
http://screenshots.sytura.de/chrome_2017-05-31_09-51-36.png

Cheers
Roland

**Comment by opi99** [comment]
Looks like part of #71 ... Maybe today evening I've time to look into this.

**Comment by sytura** [comment]
Ok. If I can test something or help you please tell me.

**Comment by opi99** [comment]
Digging through this ... it seams the sections itself are found but it doesn't get the configuration of the section elements. *wired*

**Comment by sytura** [comment]
In the documentaion of templavoila 7.6 there might be a hint. Please take a look here. Maybe it helps:

https://docs.templavoila.support/Changelog/7.6/Breaking-ConfigurationOfContainerTitlesInFlexforms.html

**Comment by opi99** [comment]
No, in TV we revert/break some breaking changes to work. :-)

Ok, I got it now (hopefully), I add a file to this issue, please test if replacing this file helps, before I commit it to git (and release):
/typo3conf/ext/templavoilaplus/Classes/Form/FormDataProvider/TcaFlexProcess.php

Please replace with following file (you need to remove the .txt extension).

[TcaFlexProcess.php.txt](https://github.com/pluspol-interactive/templavoilaplus/files/1060919/TcaFlexProcess.php.txt)

**Comment by opi99** [comment]
Also tests with TYPO3 v7 LTS are welcome.
