### ISSUE TITLE
"Page uses content from this page: ..." Link broken

### ISSUE THREAD

**Issue by mickeyk42** [pluspol-interactive/templavoilaplus#77]
If a pages uses content from another page, there ist a flash message directing to that page. The link is displayed as raw html instead of a clickable link. 

This can simply be fixed in Resources/Private/Templates/Module.html: Replace
`<div class="alert-message">{flashMessage.message}</div>`
with
`<div class="alert-message"><f:format.html>{flashMessage.message}</f:format.html></div>`

**Comment by opi99** [comment]
I don't want HTML in the flash messages, as they ma be showed by someone else. So fixing this as it was fixed for the shortcuts.
Also change from warning to info.
