### ISSUE TITLE
PHP Warning: Illegal string offset 'meta' in...

### ISSUE THREAD

**Issue by echavaillaz** [pluspol-interactive/templavoilaplus#83]
Hi,

There is a bug in the flex form tools. After deleting a tt_content ans trying to clear the deleted records with the recycler ext, I got this error : "PHP Warning: Illegal string offset 'meta' in..."

The problems is solved by changing lines 56 to 64 of "Classes/Configuration/FlexForm/FlexFormTools.php" with : 

```
            $editData = GeneralUtility::xml2array($xmlData);
            if (!is_array($editData)) {
                $editData = array();
            }

            // Language settings:
            $langChildren = 0;
            $langDisabled = 0;
            if (isset($dataStructArray['meta'])) {
                $langChildren = $dataStructArray['meta']['langChildren'] ? 1 : 0;
                $langDisabled = $dataStructArray['meta']['langDisable'] ? 1 : 0;
            }
            // Empty or invalid <meta>
            if (!isset($editData['meta'])) {
                $editData['meta'] = array();
            }
```

Thanks

**Comment by opi99** [comment]
Which version of TYPO3 and which version of TemplaVoilà Plus did you use?

**Comment by echavaillaz** [comment]
TYPO3 7.6.18 with templavoilaplus from the TER.
I try also with the master.
