### ISSUE TITLE
Page Module: Creating new FCE with content drag target, doesn't allow drag and drop into it because drag target is too small

### ISSUE THREAD

**Issue by jpmschuler** [pluspol-interactive/templavoilaplus#87]
Preliminary: Create a FCE with tt_content areas, e.g. an element for multicolumn or grouping.

Step 1) Create a page with multiple tt_content elements.
Step 2) Create an empty multicolumn FCE on top of the existing tt_content elements
Step 3) Try to drag the first tt_content element below the FCE into the FCE, by dragging it up
Effect: the tt_content element will either mark a drag zone below or above the FCE but not inside it

Alternative Step 3) Try to drag the first tt_content element to the side (outside the main content column) and then try to drop it into the FCE from right or left, instead of top or bottom
Effect: works (although still could be a bit easier)

Assumption: The drop targets should be reconfigured somehow.

As I don't know how these are exactly done, I have no clue where to look for it. Probably it could be solved with a bit of CSS (or was caused by a/my prior CSS change).

This only happens if no elements are in the drop target zone already, as soon as the zone gets bigger it works at once (e.g. element in left column of FCE and right column still empty, right column has big enough drop target zone).

**Comment by opi99** [comment]
This may be an issue inside the jquery library which is used for d'n'd, I don't think it has todo with our CSS. But yes, I discovered this issue already (didn't filled an issue ;-( )
I don't think we get this till 7.1.2

**Comment by opi99** [comment]
The problem of jQuery.UI sortable is the stupidity of calculation the next possible position. This calculation do not expect that a connected container may be inside the container in request.
With a change I will reduce the issue and it also makes the viewed drop area smaller which lets you handle this beast a bit better (but not perfectly).

**Comment by opi99** [comment]
And following will stay open:

* Scroll down and drag an element
* drag an element and move it outside of his own container
* The drag element gets offseted to top and do not stay under the cursor.

But I don't get this fixed. :-(
