### ISSUE TITLE
Uncheck of htmlspecialchars for a field not possible

### ISSUE THREAD

**Issue by onlinenow** [pluspol-interactive/templavoilaplus#88]
In configuration of a field, the pass content trough htmlspecialchars can not be unchecked. The checkbox is checked again after saving.

Tested with the latest master and TYPO3 7.6.19.

Workaround is to manually edit the HSC value in the XML.

**Comment by opi99** [comment]
Hmmm, I've the issue that I can't check the box. After pressing "Update" it is unchecked again.
