### ISSUE TITLE
Classic page module is not working

### ISSUE THREAD

**Issue by mdittberner** [pluspol-interactive/templavoilaplus#89]
When I have activated the classic page module (in my case for a second page in tree with fluidcontent) in the TV+ settings, the module seems to work. But when I create a new content element then after choosing anything in the wizard - the empty TV module is shown instead of the new content element form.

Tested with TV+ 7.1.1 on TYPO3 7.6.19.

**Comment by Kitzberger** [comment]
Thanks @opi99  ;)
