### ISSUE TITLE
v8: Error when trying to add element in section of a content element

### ISSUE THREAD

**Issue by mz-aimcom** [pluspol-interactive/templavoilaplus#90]
If I click the button to add a new element in a section, the AJAX call results in an exception:

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1478345642: Identifier could not be decoded to an array. | RuntimeException thrown in file /var/www/install/typo3_src-8.7.1/typo3/sysext/core/Classes/Configuration/FlexForm/FlexFormTools.php in line 583.

My request's POST data looks like this:
```
vanillaUid:93
databaseRowUid:93
command:edit
tableName:tt_content
fieldName:tx_templavoilaplus_flex
recordTypeValue:templavoilaplus_pi1
dataStructureIdentifier:
flexFormSheetName:
flexFormFieldName:field_table_body
flexFormContainerName:field_table_row
```

I'm using version 7.1.1 of templavoilaplus and version 8.7.1.

Perhaps this is linked with the issue fixed in https://github.com/pluspol-interactive/templavoilaplus/commit/cb6449cd469f14a457e143f7563547de7d166a7e.

**Comment by opi99** [comment]
Related: #31

**Comment by opi99** [comment]
Hint: If you already have the issue, you can't open the page/fce anymore. Rund the TemplaVoilà Plus Update Script for TYPO3 v8 again, this will fix the issue in the database.
